"""Guías prácticas (ES/EN). Slugs = comun.GUIAS_SLUGS."""

GUIAS = [
    # ------------------------------------------------------------------
    {
        "slug": "guia-que-hacer-tras-un-accidente",
        "icon": "alert",
        "es": {
            "titulo": "Qué hacer tras un accidente de tráfico",
            "corto": "Los pasos, en orden, para protegerte, avisar a quien corresponde y dejar el siniestro bien documentado.",
            "entradilla": "Un accidente, por pequeño que sea, pone nervioso a cualquiera. Esta guía te ayuda a actuar con calma: primero la seguridad, después los papeles y, por último, la reparación.",
            "texto": [
                ("h2", "1. Protege, avisa y socorre"),
                ("p", "Lo primero siempre son las personas. Si puedes, detén el coche en un lugar que no entorpezca el tráfico, enciende las luces de emergencia y ponte el chaleco reflectante antes de salir del vehículo. Si hay heridos, no los muevas salvo peligro inmediato (fuego, riesgo de atropello) y llama al **112**."),
                ("p", "Para señalizar el vehículo, desde el 1 de enero de 2026 la señal obligatoria en España es la **baliza V-16 conectada**, que sustituye a los triángulos de emergencia. Se coloca en el techo sin necesidad de caminar por la calzada y envía tu posición a la plataforma de la DGT. Si tu coche es de alquiler, comprueba dónde la guarda la empresa."),
                ("checks", [
                    "Luces de emergencia encendidas y chaleco puesto antes de bajar.",
                    "Baliza V-16 activada y colocada en el techo.",
                    "Ocupantes fuera de la calzada, detrás de la bionda si la hay.",
                    "112 si hay heridos, peligro en la vía o el otro conductor se marcha.",
                ]),
                ("h2", "2. Documenta lo ocurrido"),
                ("p", "Cuando todo el mundo esté a salvo, toca recopilar información. Haz fotos generales de la escena y de cerca de los daños de todos los vehículos, de las matrículas y de las señales de tráfico cercanas. Anota el lugar exacto, la hora y los datos de posibles testigos."),
                ("p", "Si hay acuerdo entre los conductores, rellenad juntos el [[parte-amistoso|parte amistoso]] (Declaración Amistosa de Accidente). Si no hay acuerdo, hay heridos o sospechas de alcohol o drogas, lo prudente es esperar a los agentes. Tienes más detalles en nuestra [guía del parte amistoso](guia-parte-amistoso.html)."),
                ("h2", "3. Comunica el siniestro a tu aseguradora"),
                ("p", "La Ley de Contrato de Seguro establece un plazo habitual de **7 días** desde que conoces el [[siniestro|siniestro]] para comunicárselo a tu compañía, salvo que tu póliza fije uno más amplio. No lo dejes para el último momento: cuanto antes lo comuniques, antes se asigna un [[perito|perito]] y antes puede empezar la reparación."),
                ("ol", [
                    "Llama al teléfono de asistencia o de siniestros de tu póliza.",
                    "Envía el parte firmado y las fotos por el canal que te indiquen.",
                    "Pide un número de expediente y guárdalo.",
                    "Indica en qué taller quieres reparar el coche.",
                ]),
                ("h2", "4. Elige dónde reparar"),
                ("p", "Tienes derecho a la [[libre-eleccion-de-taller|libre elección de taller]]: la aseguradora puede recomendarte su red, pero la decisión es tuya dentro de lo que diga tu póliza. En Green Car Service Tenerife trabajamos con tu compañía de seguros, coordinamos la visita del perito y te mantenemos informado del estado del vehículo en tiempo real."),
                ("p", "Si el coche no puede circular o prefieres no moverlo, pregúntanos por la recogida y entrega a domicilio. Y si tras el golpe hay piezas sueltas, faros rotos o algo roza al circular, no sigas conduciendo: algunos daños no se ven a simple vista."),
                ("nota", "Esta guía es orientativa. Las coberturas y plazos concretos dependen de tu póliza; ante cualquier duda, consulta con tu aseguradora o con nosotros."),
            ],
            "faq": [
                ("¿Tengo que llamar a la policía en cualquier accidente?", "No siempre. Si solo hay daños materiales y los conductores están de acuerdo, basta con el parte amistoso. Llama al 112 si hay heridos, peligro en la vía, desacuerdo o el otro conductor no quiere identificarse."),
                ("¿Sigo pudiendo usar los triángulos?", "Desde el 1 de enero de 2026 la señal obligatoria es la baliza V-16 conectada, que sustituye a los triángulos. Llévala siempre a mano en el habitáculo."),
                ("¿Qué pasa si comunico el siniestro después de 7 días?", "La aseguradora podría reclamarte los perjuicios causados por el retraso. Por eso conviene avisar cuanto antes, aunque todavía no tengas todos los datos."),
                ("¿Podéis recoger mi coche si no arranca tras el golpe?", "Ofrecemos recogida y entrega a domicilio. Llámanos o escríbenos por WhatsApp y vemos juntos la mejor opción según el estado del vehículo."),
            ],
        },
        "en": {
            "titulo": "What to do after a road accident",
            "corto": "The steps, in order, to keep yourself safe, notify the right people and document the incident properly.",
            "entradilla": "Any accident, however minor, is stressful. This guide helps you act calmly: safety first, then the paperwork, and finally the repair.",
            "texto": [
                ("h2", "1. Protect, call for help, assist"),
                ("p", "People always come first. If you can, stop where you will not block traffic, switch on your hazard lights and put on your high-visibility vest before getting out. If anyone is hurt, do not move them unless there is immediate danger (fire, risk of being hit) and call **112**, which has English-speaking operators."),
                ("p", "To warn other drivers, since 1 January 2026 the compulsory device in Spain is the **connected V-16 beacon**, which replaces warning triangles. You place it on the roof without walking along the carriageway, and it sends your location to the DGT (Spanish traffic authority) platform. If you are driving a hire car, check where the company keeps it."),
                ("checks", [
                    "Hazard lights on and vest on before stepping out.",
                    "V-16 beacon switched on and placed on the roof.",
                    "Passengers off the road, behind the crash barrier if there is one.",
                    "Call 112 if anyone is injured, the road is dangerous or the other driver leaves.",
                ]),
                ("h2", "2. Record what happened"),
                ("p", "Once everyone is safe, gather information. Take wide photos of the scene and close-ups of the damage to every vehicle, the number plates and nearby road signs. Note the exact location, the time and the details of any witnesses."),
                ("p", "If the drivers agree on what happened, fill in the [[parte-amistoso|accident report form]] together (the Spanish 'Declaración Amistosa de Accidente'). If you disagree, someone is hurt or you suspect alcohol or drugs, it is wiser to wait for the police. There is more detail in our [accident report form guide](guia-parte-amistoso.html)."),
                ("h2", "3. Notify your insurer"),
                ("p", "Spain's Insurance Contract Act sets a usual deadline of **7 days** from when you become aware of the [[siniestro|claim event]] to notify your insurer, unless your policy allows longer. Do not leave it until the last minute: the sooner you report it, the sooner a [[perito|loss adjuster]] is assigned and the repair can begin."),
                ("ol", [
                    "Call your policy's assistance or claims line.",
                    "Send the signed form and photos through the channel they tell you.",
                    "Ask for a claim reference number and keep it safe.",
                    "Tell them which workshop you want to repair your car.",
                ]),
                ("h2", "4. Choose where to repair"),
                ("p", "You are entitled to [[libre-eleccion-de-taller|free choice of repairer]]: your insurer may recommend its network, but the decision is yours within the terms of your policy. At Green Car Service Tenerife we work with your insurance company, coordinate the adjuster's visit and keep you updated on your car's status in real time."),
                ("p", "If the car cannot be driven, or you would rather not move it, ask us about home collection and delivery. And if after the impact there are loose parts, broken lights or something rubs as you drive, stop driving: some damage is not visible at first glance."),
                ("nota", "This guide is for general information. Specific cover and deadlines depend on your policy; if in doubt, check with your insurer or with us."),
            ],
            "faq": [
                ("Do I have to call the police after every accident?", "Not always. If there is only material damage and the drivers agree, the accident report form is enough. Call 112 if anyone is injured, the road is dangerous, you disagree or the other driver will not identify themselves."),
                ("Can I still use warning triangles?", "Since 1 January 2026 the compulsory device is the connected V-16 beacon, which replaces triangles. Keep it within easy reach inside the car."),
                ("What happens if I report the claim after 7 days?", "The insurer could hold you responsible for any loss caused by the delay. That is why it is best to notify them straight away, even if you do not have all the details yet."),
                ("Can you collect my car if it will not start after the accident?", "We offer home collection and delivery. Call us or message us on WhatsApp and we will work out the best option depending on the car's condition."),
            ],
        },
    },
    # ------------------------------------------------------------------
    {
        "slug": "guia-parte-amistoso",
        "icon": "doc",
        "es": {
            "titulo": "Cómo rellenar el parte amistoso",
            "corto": "Casilla a casilla: cómo completar la Declaración Amistosa de Accidente sin errores que luego compliquen tu reclamación.",
            "entradilla": "El parte amistoso es el documento que más ayuda a resolver un siniestro con rapidez. Bien rellenado, evita discusiones; mal rellenado, puede complicar mucho las cosas.",
            "texto": [
                ("h2", "Qué es y para qué sirve"),
                ("p", "La Declaración Amistosa de Accidente, conocida como [[parte-amistoso|parte amistoso]], es un formulario que firman los conductores implicados para dejar constancia de cómo ocurrió el accidente. Tu aseguradora lo usa para decidir quién es responsable y gestionar la reparación. Tiene dos columnas (vehículo A y vehículo B) y una zona común."),
                ("p", "Lleva siempre un ejemplar en la guantera. Si vas en un coche de alquiler, la empresa suele incluirlo en la documentación del vehículo; en inglés se suele llamar «European Accident Statement» y es el mismo modelo en muchos países europeos."),
                ("h2", "Paso a paso"),
                ("ol", [
                    "Rellena la fecha, la hora y el lugar exacto del accidente, e indica si hay heridos o daños a otros bienes.",
                    "Anota los datos de posibles testigos: nombre, teléfono y dirección.",
                    "Cada conductor completa su columna: datos personales, del vehículo, de la aseguradora y número de póliza.",
                    "Marca en el apartado de circunstancias las casillas que describen lo que hacía cada vehículo y escribe el número total de casillas marcadas.",
                    "Dibuja un croquis sencillo: vías, sentido de circulación, posición de los coches en el momento del choque y señales.",
                    "Señala con una flecha el punto de impacto inicial en cada vehículo y describe los daños visibles.",
                    "Firmad ambos conductores y quedaos cada uno con una copia.",
                ]),
                ("h2", "Errores habituales que conviene evitar"),
                ("checks", [
                    "Firmar sin estar de acuerdo con lo que pone: si no lo estás, no firmes y avisa a los agentes.",
                    "Olvidar contar las casillas marcadas, lo que permite añadir otras después.",
                    "Hacer tachones o añadir datos cuando el otro conductor ya se ha ido.",
                    "No hacer fotos de los daños, las matrículas y la documentación del otro vehículo.",
                    "Dejar el croquis en blanco o con dibujos confusos.",
                ]),
                ("p", "En el apartado de observaciones puedes anotar cualquier detalle que consideres importante. Lo que se firma conjuntamente es lo que tiene más valor, así que tómate tu tiempo antes de firmar."),
                ("h2", "Después de firmarlo"),
                ("p", "Envía tu copia a tu aseguradora cuanto antes. El plazo habitual para comunicar el [[siniestro|siniestro]] es de 7 días, según la Ley de Contrato de Seguro, salvo que tu póliza indique otro mayor. Adjunta las fotos y pide un número de expediente."),
                ("p", "Si quieres reparar en Green Car Service Tenerife, díselo a tu compañía: trabajamos con aseguradoras y nos encargamos de coordinar la [[peritacion|peritación]] del vehículo. Si te surge cualquier duda al rellenarlo, puedes llamarnos o escribirnos por WhatsApp en nuestro horario (lunes a viernes, de 07:00 a 16:00)."),
                ("nota", "Si el otro conductor no tiene seguro, se da a la fuga o hay heridos, no te limites al parte amistoso: llama al 112 para que acudan los agentes."),
            ],
            "faq": [
                ("¿Tiene validez un parte amistoso sin la firma del otro conductor?", "Sirve como tu declaración, pero pierde gran parte de su fuerza. Si no hay acuerdo, lo recomendable es que intervengan los agentes y que cada uno comunique su versión a su aseguradora."),
                ("¿Puedo rellenar el parte en inglés?", "Sí. El modelo europeo es el mismo en muchos países, de modo que las casillas numeradas coinciden aunque el idioma sea distinto. Lo importante es que ambos conductores entiendan lo que firman."),
                ("¿Qué hago si me doy cuenta de un error después de firmar?", "No lo corrijas por tu cuenta en tu copia. Explica el error a tu aseguradora cuanto antes y aporta las pruebas que tengas, como fotos o testigos."),
                ("¿Hace falta parte si el golpe es muy pequeño?", "Si vais a reclamar al seguro, sí. Si decidís no dar parte, recuerda que algunos daños no se ven a simple vista y podrían aparecer más tarde."),
            ],
        },
        "en": {
            "titulo": "How to fill in the accident report form",
            "corto": "Box by box: how to complete the Spanish accident report form without mistakes that could complicate your claim later.",
            "entradilla": "The accident report form is the document that does most to settle a claim quickly. Filled in properly, it prevents arguments; filled in badly, it can make things much harder.",
            "texto": [
                ("h2", "What it is and what it is for"),
                ("p", "The 'Declaración Amistosa de Accidente', or [[parte-amistoso|accident report form]], is a form signed by the drivers involved to record how the accident happened. Your insurer uses it to decide who is liable and to manage the repair. It has two columns (vehicle A and vehicle B) and a shared section."),
                ("p", "Always keep a copy in the glovebox. If you are in a hire car, the company usually includes one with the vehicle documents; in English it is often called the 'European Accident Statement' and it is the same layout in many European countries."),
                ("h2", "Step by step"),
                ("ol", [
                    "Fill in the date, time and exact place of the accident, and state whether anyone is injured or other property is damaged.",
                    "Write down the details of any witnesses: name, phone number and address.",
                    "Each driver completes their own column: personal details, vehicle, insurer and policy number.",
                    "In the circumstances section, tick the boxes describing what each vehicle was doing and write the total number of boxes ticked.",
                    "Draw a simple sketch: roads, direction of travel, position of the cars at the moment of impact and road signs.",
                    "Mark the initial point of impact on each vehicle with an arrow and describe the visible damage.",
                    "Both drivers sign and each keeps a copy.",
                ]),
                ("h2", "Common mistakes to avoid"),
                ("checks", [
                    "Signing when you do not agree with what it says: if you do not agree, do not sign and call the police.",
                    "Forgetting to count the ticked boxes, which allows others to be added later.",
                    "Crossing things out or adding details after the other driver has left.",
                    "Not photographing the damage, the number plates and the other vehicle's documents.",
                    "Leaving the sketch blank or making it confusing.",
                ]),
                ("p", "In the remarks section you can note anything you think is important. What both drivers sign together carries the most weight, so take your time before signing."),
                ("h2", "After signing"),
                ("p", "Send your copy to your insurer as soon as possible. The usual deadline for reporting the [[siniestro|claim event]] is 7 days under Spain's Insurance Contract Act, unless your policy allows longer. Attach the photos and ask for a claim reference."),
                ("p", "If you want Green Car Service Tenerife to carry out the repair, tell your insurer: we work with insurance companies and coordinate the vehicle's [[peritacion|loss assessment]]. If you have any questions while filling it in, call us or message us on WhatsApp during opening hours (Monday to Friday, 07:00 to 16:00)."),
                ("nota", "If the other driver is uninsured, drives off or anyone is injured, do not rely on the form alone: call 112 so the police can attend."),
            ],
            "faq": [
                ("Is the form valid without the other driver's signature?", "It serves as your own statement, but it loses much of its weight. If you cannot agree, it is best to involve the police and for each driver to report their version to their insurer."),
                ("Can I fill in the form in English?", "Yes. The European layout is the same in many countries, so the numbered boxes match even if the language differs. What matters is that both drivers understand what they are signing."),
                ("What if I notice a mistake after signing?", "Do not correct your copy on your own. Explain the mistake to your insurer as soon as possible and provide any evidence you have, such as photos or witnesses."),
                ("Do I need a form for a very small knock?", "If anyone is going to claim on their insurance, yes. If you decide not to, bear in mind that some damage is not visible at first and may show up later."),
            ],
        },
    },
    # ------------------------------------------------------------------
    {
        "slug": "guia-libre-eleccion-de-taller",
        "icon": "handshake",
        "es": {
            "titulo": "Libre elección de taller: tus derechos",
            "corto": "Aunque pague el seguro, tú decides dónde se repara tu coche. Te explicamos cómo ejercer ese derecho paso a paso.",
            "entradilla": "Cuando tienes un siniestro, es habitual que la aseguradora te sugiera uno de sus talleres concertados. Es una opción, no una obligación: en la mayoría de los casos puedes elegir el taller que prefieras.",
            "texto": [
                ("h2", "Qué significa la libre elección de taller"),
                ("p", "La [[libre-eleccion-de-taller|libre elección de taller]] es el derecho a reparar tu vehículo en el taller que tú elijas cuando el daño está cubierto por tu seguro. La compañía puede recomendarte su red de talleres, pero no puede imponértela salvo que así lo hayas aceptado expresamente en tu póliza."),
                ("p", "Algunas pólizas ofrecen un precio más bajo a cambio de reparar solo en talleres concertados, o limitan la cobertura si eliges otro. Por eso lo primero es revisar las condiciones particulares y generales de tu contrato."),
                ("h2", "Por qué te interesa elegir tú"),
                ("checks", [
                    "Puedes ir a un taller de confianza, que conozca tu coche y cuyo trato ya conoces.",
                    "Te resulta más cómodo por cercanía o por servicios como la recogida y entrega.",
                    "Puedes pedir información clara sobre qué piezas se usan: [[recambio-original|recambio original]] o de calidad equivalente.",
                    "Tienes un único interlocutor que te explica la reparación y su [[garantia-de-reparacion|garantía]].",
                ]),
                ("h2", "Cómo ejercerla paso a paso"),
                ("ol", [
                    "Comunica el siniestro a tu aseguradora en el plazo habitual de 7 días.",
                    "Indica expresamente en qué taller quieres reparar el coche y pide que lo anoten en el expediente.",
                    "Lleva el coche al taller (o pide que lo recojan) y facilita el número de expediente.",
                    "El taller solicita la visita del perito, que valora los daños.",
                    "Una vez aprobada la valoración, se realiza la reparación y se entrega el vehículo.",
                ]),
                ("p", "Si la compañía te pone pegas, pide que te indiquen por escrito en qué cláusula de tu póliza se basan. Guardar esa comunicación te ayudará si más adelante necesitas reclamar."),
                ("p", "Ten en cuenta también que elegir taller no cambia lo que cubre tu póliza: el perito de la compañía valora los daños igual, vayas donde vayas. Lo que sí cambia es quién hace la reparación, cómo te informa durante el proceso y quién responde de ella después."),
                ("h2", "Cómo te ayudamos en Green Car Service Tenerife"),
                ("p", "Trabajamos con tu compañía de seguros, coordinamos la [[peritacion|peritación]] y te mantenemos al tanto del estado de tu coche en tiempo real. Si lo necesitas, podemos recoger y devolver el vehículo a domicilio, y la pintura que aplicamos tiene garantía vitalicia."),
                ("p", "Si tu póliza tiene [[franquicia|franquicia]] o hay algún importe que no cubre el seguro, te lo explicamos antes de empezar para que no haya sorpresas. Puedes pedirnos [presupuesto](presupuesto.html) sin compromiso o consultar cómo trabajamos los [siniestros](siniestros.html)."),
                ("nota", "Cada póliza es distinta. Esta guía no sustituye la lectura de tu contrato ni el asesoramiento de tu aseguradora o mediador."),
            ],
            "faq": [
                ("¿Puede la aseguradora negarse a pagar si no voy a su taller?", "Depende de tu póliza. Si no has aceptado expresamente reparar solo en su red, normalmente puedes elegir taller. Revisa las condiciones o pídele a la compañía que te indique la cláusula concreta."),
                ("¿Tengo que adelantar el dinero de la reparación?", "En general, cuando el siniestro está cubierto y la reparación está autorizada por la aseguradora, el pago se gestiona entre la compañía y el taller. Solo tendrías que abonar lo que no cubra la póliza, como una franquicia."),
                ("¿Funciona también si el culpable fue el otro conductor?", "Sí. En ese caso reclamas a través de tu aseguradora o de la del contrario, y también puedes indicar el taller que prefieres."),
                ("¿Trabajáis con mi aseguradora?", "Trabajamos con compañías de seguros. Llámanos con los datos de tu póliza y te confirmamos cómo gestionarlo en tu caso."),
                ("¿Puedo cambiar de taller si ya había dicho otro a la aseguradora?", "En general sí, siempre que la reparación no haya empezado. Comunícaselo a tu compañía cuanto antes para que actualice el expediente y avise al perito."),
            ],
        },
        "en": {
            "titulo": "Free choice of repairer: your rights",
            "corto": "Even when insurance pays, you decide where your car is repaired. Here is how to exercise that right step by step.",
            "entradilla": "After a claim, insurers often suggest one of their approved workshops. It is an option, not an obligation: in most cases you can choose the workshop you prefer.",
            "texto": [
                ("h2", "What free choice of repairer means"),
                ("p", "[[libre-eleccion-de-taller|Free choice of repairer]] is your right to have your vehicle repaired at the workshop of your choice when the damage is covered by your insurance. The insurer can recommend its network, but it cannot impose it unless you expressly agreed to that in your policy."),
                ("p", "Some policies offer a lower premium in exchange for using approved workshops only, or limit cover if you go elsewhere. So the first step is to check the particular and general terms of your contract."),
                ("h2", "Why it pays to choose yourself"),
                ("checks", [
                    "You can use a workshop you trust, that knows your car and whose service you already know.",
                    "It may be more convenient because of location or services such as collection and delivery.",
                    "You can ask clearly which parts will be used: [[recambio-original|original parts]] or equivalent-quality ones.",
                    "You have a single point of contact who explains the repair and its [[garantia-de-reparacion|warranty]].",
                ]),
                ("h2", "How to exercise it, step by step"),
                ("ol", [
                    "Report the claim to your insurer within the usual 7-day deadline.",
                    "State clearly which workshop you want to repair the car and ask them to record it on the claim file.",
                    "Take the car to the workshop (or ask for it to be collected) and give them the claim reference.",
                    "The workshop requests a visit from the loss adjuster, who assesses the damage.",
                    "Once the assessment is approved, the repair is carried out and the car is returned.",
                ]),
                ("p", "If the insurer raises objections, ask them to tell you in writing which clause of your policy they are relying on. Keeping that message will help if you need to make a complaint later."),
                ("p", "Bear in mind too that choosing your workshop does not change what your policy covers: the insurer's adjuster assesses the damage in the same way wherever you go. What does change is who carries out the repair, how they keep you informed and who stands behind the work afterwards."),
                ("h2", "How Green Car Service Tenerife helps"),
                ("p", "We work with your insurance company, coordinate the [[peritacion|loss assessment]] and keep you updated on your car's status in real time. If you need it, we can collect and return the vehicle to your home, and the paintwork we apply comes with a lifetime warranty."),
                ("p", "If your policy has an [[franquicia|excess]] or there is any amount your insurance does not cover, we explain it before starting so there are no surprises. You can ask us for a no-obligation [estimate](presupuesto.html) or read how we handle [insurance claims](siniestros.html)."),
                ("nota", "Every policy is different. This guide does not replace reading your contract or the advice of your insurer or broker."),
            ],
            "faq": [
                ("Can the insurer refuse to pay if I do not use their workshop?", "It depends on your policy. If you have not expressly agreed to repair only within their network, you can usually choose. Check the terms or ask the insurer to point out the specific clause."),
                ("Do I have to pay for the repair up front?", "Generally, when the claim is covered and the insurer has authorised the repair, payment is handled between the insurer and the workshop. You would only pay what the policy does not cover, such as an excess."),
                ("Does this also apply if the other driver was at fault?", "Yes. In that case you claim through your own insurer or the other party's, and you can still name the workshop you prefer."),
                ("Do you work with my insurer?", "We work with insurance companies. Call us with your policy details and we will confirm how to handle your case."),
                ("Can I switch workshop if I already named another one to my insurer?", "Generally yes, as long as the repair has not started. Let your insurer know as soon as possible so they can update the claim file and inform the adjuster."),
            ],
        },
    },
    # ------------------------------------------------------------------
    {
        "slug": "guia-peritacion",
        "icon": "clipboard",
        "es": {
            "titulo": "La peritación del coche, explicada",
            "corto": "Quién es el perito, qué revisa, cuánto suele tardar y qué puedes hacer si no estás de acuerdo con su valoración.",
            "entradilla": "Tras comunicar un siniestro, el siguiente paso suele ser la visita del perito. Entender cómo funciona te ayuda a saber qué esperar y a defender tus intereses.",
            "texto": [
                ("h2", "Qué es la peritación"),
                ("p", "La [[peritacion|peritación]] es la valoración técnica de los daños de tu vehículo. La realiza un [[perito|perito]], normalmente designado por la aseguradora, que determina qué piezas se reparan o se sustituyen, cuántas horas de trabajo hacen falta y cuánto cuesta en total la reparación."),
                ("p", "Con esa valoración, la compañía autoriza la reparación o, si el coste es muy alto respecto al valor del coche, puede plantear una [[perdida-total|pérdida total]]."),
                ("h2", "Cómo se desarrolla"),
                ("ol", [
                    "Comunicas el siniestro y eliges taller.",
                    "La aseguradora asigna un perito y el taller coordina con él la visita.",
                    "El perito inspecciona el coche en el taller, hace fotos y revisa los daños visibles.",
                    "Si al desmontar aparecen daños ocultos, el taller lo comunica y se amplía la valoración.",
                    "La compañía autoriza la reparación según el informe del perito.",
                ]),
                ("p", "En algunos casos la peritación se hace a partir de fotos o vídeo que envía el taller. El plazo depende de la carga de trabajo de la aseguradora y del perito, así que no conviene dar fechas cerradas; lo que sí ayuda es tener el coche disponible y la documentación en orden."),
                ("h2", "Qué revisa el perito"),
                ("checks", [
                    "Daños de [[carroceria|carrocería]]: chapa, paragolpes, lunas y faros.",
                    "Posibles deformaciones de estructura que requieran bancada.",
                    "Piezas interiores dañadas: refuerzos, soportes, frente interior y anclajes de carrocería.",
                    "Si conviene reparar o sustituir cada pieza, según el [[baremo|baremo]] y el método del fabricante.",
                    "Si los daños son coherentes con el siniestro declarado.",
                ]),
                ("h2", "Si no estás de acuerdo"),
                ("p", "Si crees que la valoración se queda corta o no refleja todos los daños, primero habla con el taller: a menudo basta con aportar fotos o documentación adicional para que el perito revise su informe. Si el desacuerdo persiste, la Ley de Contrato de Seguro prevé que puedas designar un perito propio. Ten en cuenta que sus honorarios pueden correr de tu cuenta según el caso."),
                ("h2", "Cómo prepararte"),
                ("checks", [
                    "Ten a mano el número de expediente y los datos de tu póliza.",
                    "Guarda las fotos que hiciste en el momento del siniestro y el parte amistoso.",
                    "Anota cualquier cosa rara que hayas notado después del golpe: puertas que cierran mal, ruidos de carrocería, piezas sueltas.",
                    "Comenta con el taller los daños previos que ya tuviera el coche, para no mezclarlos con los nuevos.",
                ]),
                ("p", "En Green Car Service Tenerife trabajamos con tu compañía de seguros y coordinamos la peritación para que no se quede nada fuera. Además, puedes seguir el estado de tu coche en tiempo real durante toda la reparación."),
                ("nota", "Los plazos y el procedimiento concreto pueden variar según la aseguradora y la póliza. Te confirmamos cada paso a medida que avanza tu expediente."),
            ],
            "faq": [
                ("¿Tengo que estar presente cuando venga el perito?", "No es necesario. Si el coche está en nuestro taller, nos encargamos de coordinar la visita y te contamos el resultado."),
                ("¿Se puede empezar a reparar antes de la peritación?", "Normalmente no, porque la aseguradora necesita ver los daños antes de autorizar el trabajo. Si hay algo urgente para poder mover el coche con seguridad, lo consultamos con la compañía."),
                ("¿Qué pasa si aparecen más daños al desmontar?", "Es habitual. Lo documentamos con fotos y pedimos una ampliación de la peritación antes de seguir."),
                ("¿El perito trabaja para mí o para la aseguradora?", "El perito designado por la compañía trabaja por encargo de ella, aunque debe actuar con criterio técnico. Si no estás conforme, puedes contratar un perito independiente."),
                ("¿Puedo usar mi coche mientras espero al perito?", "Si el golpe es leve y el coche es seguro, a veces sí. Pero si hay luces rotas, piezas sueltas o algo que roza, es mejor no circular y dejarlo en el taller hasta la visita."),
            ],
        },
        "en": {
            "titulo": "Vehicle loss assessment, explained",
            "corto": "Who the loss adjuster is, what they check, how long it usually takes and what you can do if you disagree with their assessment.",
            "entradilla": "After reporting a claim, the next step is usually the loss adjuster's visit. Understanding how it works helps you know what to expect and protect your interests.",
            "texto": [
                ("h2", "What a loss assessment is"),
                ("p", "A [[peritacion|loss assessment]] is the technical valuation of the damage to your vehicle. It is carried out by a [[perito|loss adjuster]], usually appointed by the insurer, who decides which parts are repaired or replaced, how many labour hours are needed and what the repair will cost in total."),
                ("p", "Based on that assessment, the insurer authorises the repair or, if the cost is very high compared with the car's value, may propose a [[perdida-total|total loss]]."),
                ("h2", "How it works"),
                ("ol", [
                    "You report the claim and choose a workshop.",
                    "The insurer appoints an adjuster and the workshop arranges the visit.",
                    "The adjuster inspects the car at the workshop, takes photos and reviews the visible damage.",
                    "If hidden damage appears once parts are removed, the workshop reports it and the assessment is extended.",
                    "The insurer authorises the repair according to the adjuster's report.",
                ]),
                ("p", "Sometimes the assessment is done from photos or video sent by the workshop. Timing depends on the insurer's and adjuster's workload, so it is not wise to promise fixed dates; what does help is having the car available and your paperwork in order."),
                ("h2", "What the adjuster checks"),
                ("checks", [
                    "[[carroceria|Bodywork]] damage: panels, bumpers, glass and lights.",
                    "Any structural distortion that needs a chassis jig.",
                    "Damaged inner parts: reinforcements, brackets, inner front panel and body mountings.",
                    "Whether each part should be repaired or replaced, according to the [[baremo|repair time schedule]] and the manufacturer's method.",
                    "Whether the damage matches the reported incident.",
                ]),
                ("h2", "If you disagree"),
                ("p", "If you think the assessment falls short or misses some damage, talk to the workshop first: often extra photos or documents are enough for the adjuster to review the report. If you still disagree, Spain's Insurance Contract Act allows you to appoint your own adjuster. Bear in mind that you may have to pay their fees, depending on the case."),
                ("h2", "How to prepare"),
                ("checks", [
                    "Have your claim reference and policy details to hand.",
                    "Keep the photos you took at the time of the incident and the accident report form.",
                    "Note anything odd you noticed after the impact: doors that do not shut properly, body rattles, loose parts.",
                    "Tell the workshop about any previous damage the car already had, so it is not mixed up with the new damage.",
                ]),
                ("p", "At Green Car Service Tenerife we work with your insurance company and coordinate the assessment so nothing is left out. You can also follow your car's status in real time throughout the repair."),
                ("nota", "Timescales and the exact procedure may vary depending on the insurer and policy. We confirm each step as your claim progresses."),
            ],
            "faq": [
                ("Do I need to be there when the adjuster comes?", "No. If the car is at our workshop, we arrange the visit and let you know the outcome."),
                ("Can the repair start before the assessment?", "Usually not, because the insurer needs to see the damage before authorising the work. If something urgent is needed to move the car safely, we check with the insurer."),
                ("What if more damage appears when parts are removed?", "That is common. We document it with photos and ask for the assessment to be extended before carrying on."),
                ("Does the adjuster work for me or for the insurer?", "An adjuster appointed by the insurer works on its behalf, although they must apply technical judgement. If you are not satisfied, you can hire an independent adjuster."),
                ("Can I use my car while I wait for the adjuster?", "If the damage is minor and the car is safe, sometimes yes. But if lights are broken, parts are loose or something is rubbing, it is better not to drive and to leave it at the workshop until the visit."),
            ],
        },
    },
    # ------------------------------------------------------------------
    {
        "slug": "guia-perdida-total",
        "icon": "euro",
        "es": {
            "titulo": "Pérdida total: qué significa y qué puedes hacer",
            "corto": "Cuándo declara el seguro un siniestro total, cómo se calcula la indemnización y qué opciones tienes con tu coche.",
            "entradilla": "Escuchar que tu coche es «siniestro total» es duro, sobre todo si le tienes cariño o todavía funciona. Te explicamos qué hay detrás de esa decisión y qué margen tienes.",
            "texto": [
                ("h2", "Qué es una pérdida total"),
                ("p", "Se habla de [[perdida-total|pérdida total]] cuando reparar el vehículo cuesta más que su valor, o más de un porcentaje de ese valor fijado en tu póliza. También se considera así cuando el coche ha quedado destruido o ha sido robado y no aparece. La decisión se toma a partir del informe del [[perito|perito]]."),
                ("p", "Que el seguro declare pérdida total no significa que el coche no se pueda reparar técnicamente, sino que económicamente no compensa según las condiciones del contrato."),
                ("h2", "Valor venal y valor de mercado"),
                ("p", "Son los dos conceptos que más aparecen en estos casos, y conviene no confundirlos:"),
                ("checks", [
                    "**Valor venal**: lo que valía tu coche justo antes del siniestro, teniendo en cuenta su antigüedad y desgaste. Suele ser la cifra más baja.",
                    "**Valor de mercado**: lo que te costaría comprar un coche de características similares (marca, modelo, año, kilómetros y estado). Suele ser algo más alto.",
                    "**Valor a nuevo**: algunas pólizas a [[todo-riesgo|todo riesgo]] lo garantizan durante los primeros años del vehículo.",
                ]),
                ("p", "Qué valor se aplica depende de si el seguro es tuyo o del contrario y de lo que diga tu póliza. Si el culpable es el otro conductor, la jurisprudencia suele tener en cuenta el valor venal más un porcentaje adicional, conocido como valor de afección, aunque cada caso se estudia por separado."),
                ("h2", "Qué opciones tienes"),
                ("ol", [
                    "Aceptar la indemnización y entregar el vehículo a la aseguradora, que gestiona su baja o su venta.",
                    "Quedarte con el coche (los restos) a cambio de una indemnización menor, y repararlo por tu cuenta si te compensa.",
                    "Pedir una revisión si crees que la valoración no se ajusta al mercado, aportando anuncios de coches similares o un informe de un perito independiente.",
                ]),
                ("p", "Antes de decidir, lee bien tu póliza y pide por escrito el cálculo de la indemnización. Si tienes [[franquicia|franquicia]], comprueba si se descuenta."),
                ("p", "Si aceptas la indemnización, la compañía te pedirá normalmente la documentación del vehículo (permiso de circulación y ficha técnica), las llaves y algún documento firmado de cesión. Si el coche estaba financiado, puede que parte del pago vaya directamente a la entidad financiera. Pregunta también qué pasa con el impuesto de circulación y con el seguro que ya habías pagado."),
                ("h2", "Cómo te podemos ayudar"),
                ("p", "Si decides reparar el coche pese a la pérdida total, te preparamos un [[presupuesto|presupuesto]] realista para que compares. Y si prefieres cambiar de vehículo, también vendemos [coches de ocasión](coches-de-ocasion.html), revisados en nuestro propio taller."),
                ("nota", "La normativa y la jurisprudencia sobre indemnizaciones son complejas y dependen de cada caso. Esta guía es orientativa; para decisiones importantes, consulta con tu aseguradora o con un profesional."),
            ],
            "faq": [
                ("¿Puedo quedarme con mi coche si el seguro lo declara pérdida total?", "Normalmente sí, aunque la aseguradora descontará el valor de los restos de la indemnización. Pídeles que te detallen las cifras antes de decidir."),
                ("¿Me pagan lo que costó el coche?", "Salvo que tu póliza incluya valor a nuevo, lo habitual es que te indemnicen según el valor venal o de mercado, que es menor que el precio de compra."),
                ("¿Qué hago si la cifra me parece baja?", "Busca anuncios de coches equivalentes y preséntalos a la compañía. También puedes encargar un informe a un perito independiente."),
                ("¿Me podéis ayudar a buscar otro coche?", "Sí. Tenemos coches de ocasión y te contamos qué revisiones les hemos hecho antes de venderlos."),
                ("¿Cuánto tarda en pagar la aseguradora?", "Depende de cada compañía y de que la documentación esté completa. Entregar todo cuanto antes y pedir confirmación por escrito suele agilizar el proceso."),
            ],
        },
        "en": {
            "titulo": "Total loss: what it means and what you can do",
            "corto": "When insurers write a car off, how the payout is worked out and what options you have with your vehicle.",
            "entradilla": "Hearing that your car is a 'write-off' is hard, especially if you are fond of it or it still runs. Here is what lies behind that decision and how much room you have.",
            "texto": [
                ("h2", "What a total loss is"),
                ("p", "A car is declared a [[perdida-total|total loss]] when repairing it would cost more than it is worth, or more than a percentage of that value set in your policy. It also applies when the car is destroyed or stolen and not recovered. The decision is based on the [[perito|loss adjuster's]] report."),
                ("p", "A total loss does not mean the car cannot be repaired technically; it means repair does not make financial sense under the terms of the contract."),
                ("h2", "Pre-accident value and market value"),
                ("p", "These are the two terms that come up most in these cases, and it is worth keeping them apart:"),
                ("checks", [
                    "**Pre-accident value** ('valor venal'): what your car was worth just before the incident, allowing for age and wear. It is usually the lowest figure.",
                    "**Market value** ('valor de mercado'): what it would cost you to buy a similar car (make, model, year, mileage and condition). It is usually somewhat higher.",
                    "**New-for-old value**: some [[todo-riesgo|comprehensive]] policies guarantee it for the first few years of the vehicle's life.",
                ]),
                ("p", "Which value applies depends on whether the claim is on your insurance or the other party's, and on your policy wording. If the other driver was at fault, Spanish courts often consider the pre-accident value plus an extra percentage, known as 'valor de afección', although each case is assessed on its own."),
                ("h2", "What your options are"),
                ("ol", [
                    "Accept the payout and hand the car over to the insurer, which arranges its deregistration or sale.",
                    "Keep the car (the salvage) in exchange for a lower payout, and repair it yourself if it is worth it.",
                    "Ask for a review if you think the valuation does not reflect the market, providing adverts for similar cars or a report from an independent adjuster.",
                ]),
                ("p", "Before deciding, read your policy carefully and ask for the payout calculation in writing. If you have an [[franquicia|excess]], check whether it is deducted."),
                ("p", "If you accept the payout, the insurer will normally ask for the vehicle documents (registration certificate and technical sheet), the keys and a signed transfer document. If the car was on finance, part of the payment may go directly to the lender. Ask too what happens to the road tax and to any insurance premium you have already paid."),
                ("h2", "How we can help"),
                ("p", "If you decide to repair the car despite the total loss, we will prepare a realistic [[presupuesto|repair estimate]] so you can compare. And if you would rather replace it, we also sell [used cars](coches-de-ocasion.html), checked over in our own workshop."),
                ("nota", "Rules and case law on payouts are complex and depend on each case. This guide is for general information; for important decisions, speak to your insurer or a professional."),
            ],
            "faq": [
                ("Can I keep my car if the insurer writes it off?", "Usually yes, although the insurer will deduct the salvage value from the payout. Ask them for a breakdown of the figures before deciding."),
                ("Will I get back what I paid for the car?", "Unless your policy includes new-for-old cover, you will normally be paid the pre-accident or market value, which is lower than the purchase price."),
                ("What if the figure seems too low?", "Look for adverts for equivalent cars and send them to the insurer. You can also commission a report from an independent adjuster."),
                ("Can you help me find another car?", "Yes. We have used cars for sale and will tell you what checks we have carried out before selling them."),
                ("How long does the insurer take to pay?", "It depends on the company and on the paperwork being complete. Handing everything over promptly and asking for written confirmation usually speeds things up."),
            ],
        },
    },
    # ------------------------------------------------------------------
    {
        "slug": "guia-comprar-coche-de-ocasion",
        "icon": "search",
        "es": {
            "titulo": "Guía para comprar un coche de ocasión",
            "corto": "Qué documentos pedir, qué revisar antes de pagar y qué garantía te corresponde al comprar un coche usado.",
            "entradilla": "Un coche de segunda mano puede ser una compra excelente o un quebradero de cabeza. La diferencia está casi siempre en lo que compruebas antes de firmar.",
            "texto": [
                ("h2", "Antes de ver el coche: los papeles"),
                ("p", "Empieza por la documentación. Con la matrícula puedes pedir el **[[informe-dgt|informe del vehículo de la DGT]]**, que muestra el titular, las cargas o embargos, el historial de [[itv|ITV]] y los kilómetros registrados en las inspecciones. Si los kilómetros no cuadran con el cuentakilómetros, desconfía."),
                ("checks", [
                    "Informe de la DGT sin cargas ni embargos pendientes.",
                    "Permiso de circulación y ficha técnica que coincidan con el coche.",
                    "ITV en vigor y resultados de las últimas inspecciones.",
                    "Facturas de reparaciones anteriores, sobre todo de chapa y pintura.",
                    "Recibo del impuesto de circulación del año en curso.",
                ]),
                ("h2", "Qué revisar en persona"),
                ("p", "Mira el coche a plena luz del día. Diferencias de tono entre piezas, holguras irregulares entre puertas o restos de pintura en gomas pueden indicar reparaciones de [[carroceria|carrocería]]. No es necesariamente malo, pero conviene saber qué pasó."),
                ("ol", [
                    "Agáchate y mira cada lateral a contraluz: ondulaciones o zonas con distinto brillo delatan masilla o repintados.",
                    "Comprueba que las holguras entre capó, aletas, puertas y portón son iguales en ambos lados.",
                    "Abre puertas, capó y maletero: busca soldaduras que no parecen de fábrica, sellador irregular o arrugas en la chapa interior.",
                    "Fíjate en lunas, faros y pilotos: si uno es distinto de los demás, puede haberse cambiado tras un golpe.",
                    "Busca óxido en bajos y arcos de rueda, sobre todo si el coche ha vivido cerca del mar.",
                ]),
                ("p", "Si puedes, pide que un taller de confianza revise la carrocería antes de comprarlo. Con un [[medidor-de-espesores|medidor de espesores de pintura]] se detectan piezas repintadas o con masilla, y una revisión de los bajos y de las uniones interiores permite ver si el coche ha tenido un golpe de estructura. Lo hacemos en nuestra [revisión antes de comprar](revision-antes-de-comprar.html), con un informe con fotos."),
                ("h2", "Particular o profesional: la garantía"),
                ("p", "Si compras a un **profesional**, la ley te reconoce una garantía legal que, para bienes de segunda mano, puede pactarse por un mínimo de **un año**. Cubre las faltas de conformidad, es decir, defectos que el coche ya tenía o que no se corresponden con lo anunciado. Pide siempre factura y las condiciones de la garantía por escrito."),
                ("p", "Si compras a un **particular**, no existe esa garantía comercial, aunque sí puedes reclamar por vicios ocultos graves en determinados plazos. Por eso, en compras entre particulares, la revisión previa es todavía más importante."),
                ("p", "Tras la compra, recuerda que hay que tramitar el cambio de titularidad ante la DGT y pagar el impuesto correspondiente. Cuando compras a un profesional, lo habitual es que se encargue él de la gestión; confírmalo antes de firmar."),
                ("h2", "Nuestros coches de ocasión"),
                ("p", "En Green Car Service Tenerife también vendemos coches de segunda mano. Los revisamos en nuestro propio taller antes de ponerlos a la venta y te contamos qué se ha hecho en cada uno. Consulta la disponibilidad en [coches de ocasión](coches-de-ocasion.html) o llámanos; si ya tienes uno a la vista en otro sitio, también podemos ayudarte a revisarlo."),
                ("nota", "Los plazos y condiciones de garantía dependen del tipo de venta y del contrato. Te los confirmamos por escrito en cada caso."),
            ],
            "faq": [
                ("¿Cómo consigo el informe de la DGT?", "Puedes solicitarlo en la sede electrónica de la DGT o en sus oficinas indicando la matrícula. Tiene un coste reducido y es la mejor forma de evitar sorpresas."),
                ("¿Qué garantía tienen los coches de ocasión que vendéis?", "Como vendedores profesionales, respetamos la garantía legal que corresponde. Te detallamos las condiciones de cada coche por escrito antes de la compra."),
                ("¿Podéis revisar un coche que quiero comprar en otro sitio?", "Sí. Tráelo al taller en nuestro horario y revisamos carrocería, pintura, estructura y documentación para que decidas con información. Más detalles en [revisión antes de comprar](revision-antes-de-comprar.html)."),
                ("¿Es malo que un coche usado tenga piezas repintadas?", "No necesariamente. Muchas reparaciones están bien hechas. Lo importante es saber qué ocurrió y comprobar que no afecta a la estructura."),
            ],
        },
        "en": {
            "titulo": "A guide to buying a used car",
            "corto": "Which documents to ask for, what to check before paying and what warranty you are entitled to when buying second-hand.",
            "entradilla": "A second-hand car can be an excellent buy or a real headache. The difference almost always lies in what you check before signing.",
            "texto": [
                ("h2", "Before viewing: the paperwork"),
                ("p", "Start with the documents. Using the number plate, you can request the **[[informe-dgt|DGT vehicle report]]** (from the Spanish traffic authority), which shows the registered keeper, any charges or liens, the [[itv|ITV (MOT)]] history and the mileage recorded at inspections. If the mileage does not match the odometer, be wary."),
                ("checks", [
                    "DGT report with no outstanding charges or liens.",
                    "Registration certificate and technical sheet that match the car.",
                    "Valid ITV and results of the latest inspections.",
                    "Invoices for previous repairs, especially bodywork and paint.",
                    "Road tax receipt for the current year.",
                ]),
                ("h2", "What to check in person"),
                ("p", "View the car in full daylight. Colour differences between panels, uneven gaps between doors or paint on rubber seals can point to [[carroceria|bodywork]] repairs. That is not necessarily bad, but you should know what happened."),
                ("ol", [
                    "Crouch down and look along each side against the light: ripples or patches with a different gloss give away filler or respraying.",
                    "Check that the gaps between bonnet, wings, doors and tailgate are the same on both sides.",
                    "Open the doors, bonnet and boot: look for welds that do not look factory-made, uneven sealer or creased inner panels.",
                    "Look at the glass, headlights and rear lights: if one differs from the rest, it may have been replaced after a knock.",
                    "Look for rust on the underbody and wheel arches, especially if the car has lived near the sea.",
                ]),
                ("p", "If you can, ask a workshop you trust to inspect the bodywork before buying. A [[medidor-de-espesores|paint thickness gauge]] picks up resprayed or filled panels, and a look at the underbody and inner joints shows whether the car has had a structural impact. We do this in our [pre-purchase inspection](revision-antes-de-comprar.html), with a report and photos."),
                ("h2", "Private seller or dealer: the warranty"),
                ("p", "If you buy from a **dealer or professional seller**, Spanish law gives you a legal guarantee which, for second-hand goods, may be set at no less than **one year**. It covers lack of conformity, meaning faults the car already had or features that do not match the advert. Always ask for an invoice and the warranty terms in writing."),
                ("p", "If you buy from a **private seller**, there is no such guarantee, although you may be able to claim for serious hidden defects within certain time limits. That makes an inspection before buying even more important."),
                ("p", "After buying, remember that the change of ownership has to be registered with the DGT and the relevant tax paid. When you buy from a professional, they usually handle the paperwork; confirm this before signing."),
                ("h2", "Our used cars"),
                ("p", "Green Car Service Tenerife also sells second-hand cars. We check them in our own workshop before putting them on sale and tell you what has been done on each one. See what is available in [used cars](coches-de-ocasion.html) or give us a call; if you already have your eye on one elsewhere, we can help you check it too."),
                ("nota", "Warranty periods and terms depend on the type of sale and the contract. We confirm them in writing in each case."),
            ],
            "faq": [
                ("How do I get the DGT report?", "You can request it from the DGT's online portal or at its offices using the number plate. It costs little and is the best way to avoid surprises."),
                ("What warranty do your used cars come with?", "As a professional seller, we honour the applicable legal guarantee. We set out the terms for each car in writing before you buy."),
                ("Can you inspect a car I am thinking of buying elsewhere?", "Yes. Bring it to the workshop during opening hours and we will check the bodywork, paint, structure and paperwork so you can decide with the facts. More details in [pre-purchase inspection](revision-antes-de-comprar.html)."),
                ("Is it bad if a used car has resprayed panels?", "Not necessarily. Many repairs are well done. What matters is knowing what happened and checking that the structure has not been affected."),
            ],
        },
    },
]
