"""Fichas por tipo de cliente (ES/EN)."""

SERVICIOS = [
# ---------------------------------------------------------------------------
{
  "slug": "particulares", "cat": "clientes", "icon": "users",
  "es": {
    "titulo": "Particulares",
    "corto": "Golpes, arañazos, accidentes o pintura: reparamos tu coche con presupuesto por escrito, pague tu seguro o pagues tú.",
    "entradilla": "Tu coche es parte de tu día a día y quieres recuperarlo bien reparado y cuanto antes. En Green Car Service nos ocupamos de la chapa y la pintura y te lo ponemos fácil de principio a fin.",
    "por_que_titulo": "Por qué confiar tu coche a Green Car",
    "por_que": [
      ("handshake", "Trato cercano", "Te explicamos qué tiene tu coche y qué vamos a hacer, sin tecnicismos. Desde 2019 trabajamos para ganarnos la confianza de cada cliente."),
      ("award", "Garantía vitalicia en pintura", "Los trabajos de pintura tienen garantía vitalicia en las condiciones que te detallamos al entregarte el coche."),
      ("star", "Lo dicen nuestros clientes", "Tenemos una valoración de 4,8 sobre 5 con 177 opiniones en Google. Muchos destacan que entregamos el coche limpio, también por dentro."),
    ],
    "incluye_titulo": "Qué hacemos por ti",
    "incluye_intro": "Todo lo que tenga que ver con la carrocería y la pintura de tu coche, desde un roce hasta un accidente.",
    "incluye": [
      ("hammer", "Golpes y abolladuras", "Bollos de aparcamiento, golpes en puertas y aletas y reparación de chapa tras un accidente."),
      ("spray", "Arañazos y pintura", "Retoques, pintura parcial o completa y pulido, con pintura ecológica y colores sólidos y metalizados."),
      ("shield", "Con tu seguro o por tu cuenta", "Gestionamos el [[siniestro|siniestro]] con tu compañía o, si lo prefieres, pagas tú con presupuesto cerrado."),
      ("truck", "Recogida y entrega", "Podemos recoger tu coche y devolvértelo reparado, según zona y disponibilidad."),
      ("eye", "Estado en tiempo real", "Sabes en qué fase está la reparación sin tener que llamar."),
      ("car", "Vehículo de sustitución", "Según disponibilidad o lo que cubra tu póliza, para que no te quedes sin coche."),
    ],
    "nota": "Cada reparación es distinta. El plazo, el coste y si hay vehículo de sustitución te los confirmamos en el presupuesto, antes de empezar.",
    "texto": [
      ("h2", "Así trabajamos contigo"),
      ("checks", [
        "**Nos cuentas qué le ha pasado al coche**, por teléfono, WhatsApp o en el taller. Si nos mandas fotos, te podemos dar una primera idea.",
        "**Lo vemos y te damos presupuesto por escrito.** Es tu derecho como cliente de un taller y no hacemos nada sin tu aprobación.",
        "**Reparamos** con bancadas y el equipamiento necesario para trabajar según los estándares de cada marca.",
        "**Te informamos del estado** mientras está en el taller.",
        "**Te lo entregamos limpio**, con la factura y la [[garantia-de-reparacion|garantía de la reparación]].",
      ]),
      ("h2", "Si ha habido un accidente"),
      ("p", "Un golpe siempre es un mal rato. Si ha sido con otro vehículo, rellena bien el [[parte-amistoso|parte amistoso]] y llámanos. Te ayudamos con los pasos siguientes: la apertura del siniestro, la visita del perito y la reparación. Tienes más información en nuestra página de [siniestros](siniestros.html) y en la [guía de qué hacer tras un accidente](guia-que-hacer-tras-un-accidente.html)."),
      ("p", "Recuerda que puedes elegir el taller que quieras para reparar tu coche. Es lo que se conoce como [[libre-eleccion-de-taller|libre elección de taller]], y la aseguradora no puede obligarte a ir a uno concreto. Te lo explicamos en la [guía de libre elección de taller](guia-libre-eleccion-de-taller.html)."),
      ("h2", "Si prefieres pagar tú"),
      ("p", "A veces no compensa dar parte: un roce pequeño, un arañazo de parking o una [[franquicia|franquicia]] que no merece la pena usar. En esos casos te damos un [presupuesto sin compromiso](presupuesto.html) y decides con calma. Si solo quieres recuperar el brillo o mejorar el aspecto, también podemos pulir la pintura o restaurar los faros."),
      ("p", "Tanto si paga el seguro como si pagas tú, el trabajo es el mismo: reparamos con el mismo cuidado, usamos pintura ecológica «eco-balance» y te damos la misma garantía. Y si la reparación la cubre tu compañía, nos encargamos de coordinarnos con ella para que tú no tengas que hacer de intermediario."),
      ("h2", "Pensado para el sur de Tenerife"),
      ("p", "Estamos en Las Chafiras, en el polígono de Llano del Camello, muy cerca de la TF-1. Atendemos a vecinos de todo el sur, a residentes extranjeros y a quienes pasan aquí parte del año. Nuestro horario es de lunes a viernes de 07:00 a 16:00. Si no te viene bien acercarte, pregúntanos por la recogida y entrega. Para empezar, [pide cita](pedir-cita.html) o escríbenos."),
    ],
    "faq": [
      ("¿Tengo que ir al taller que me diga mi seguro?", "No. Tienes derecho a elegir taller. Si eliges el nuestro, nos coordinamos con tu compañía y con el perito."),
      ("¿Me dais presupuesto antes de reparar?", "Sí, siempre por escrito y antes de empezar. No hacemos ningún trabajo sin tu aprobación."),
      ("¿Tenéis coche de sustitución?", "Depende de la disponibilidad y de lo que cubra tu póliza. Te lo confirmamos al organizar la reparación."),
      ("¿Qué cubre la garantía vitalicia en pintura?", "Cubre los trabajos de pintura que hacemos, en las condiciones que te detallamos por escrito al entregarte el coche."),
      ("¿Atendéis en inglés?", "Sí, atendemos a muchos residentes y visitantes extranjeros. Escríbenos y te respondemos."),
    ],
  },
  "en": {
    "titulo": "Private customers",
    "corto": "Dents, scratches, accidents or paintwork: we repair your car with a written estimate, whether your insurer pays or you do.",
    "entradilla": "Your car is part of your everyday life and you want it back properly repaired as soon as possible. At Green Car Service we take care of the bodywork and paint and make it easy from start to finish.",
    "por_que_titulo": "Why trust your car to Green Car",
    "por_que": [
      ("handshake", "A personal service", "We explain what is wrong with your car and what we are going to do, without jargon. Since 2019 we have worked to earn every customer's trust."),
      ("award", "Lifetime paint warranty", "Paintwork carries a lifetime warranty under the conditions we set out when we hand the car back."),
      ("star", "Our customers say so", "We are rated 4.8 out of 5 from 177 Google reviews. Many mention that we return the car clean, inside too."),
    ],
    "incluye_titulo": "What we do for you",
    "incluye_intro": "Anything to do with your car's bodywork and paint, from a scrape to an accident.",
    "incluye": [
      ("hammer", "Dents and knocks", "Car-park dings, dents in doors and wings, and bodywork repair after an accident."),
      ("spray", "Scratches and paint", "Touch-ups, partial or full resprays and polishing, with eco-friendly paint in solid and metallic colours."),
      ("shield", "Through your insurer or yourself", "We handle the [[siniestro|claim]] with your insurer or, if you prefer, you pay with a fixed estimate."),
      ("truck", "Collection and delivery", "We can collect your car and bring it back repaired, depending on the area and availability."),
      ("eye", "Real-time status", "You know what stage the repair is at without having to phone."),
      ("car", "Courtesy car", "Depending on availability or what your policy covers, so you are not left without a car."),
    ],
    "nota": "Every repair is different. We confirm the timing, the cost and whether a courtesy car is available in the estimate, before we start.",
    "texto": [
      ("h2", "How we work with you"),
      ("checks", [
        "**Tell us what happened to the car**, by phone, WhatsApp or at the workshop. If you send photos, we can give you a first idea.",
        "**We look at it and give you a written estimate.** It is your right as a workshop customer and we do nothing without your approval.",
        "**We repair it** using chassis jigs and the equipment needed to work to each manufacturer's standards.",
        "**We keep you updated** while it is with us.",
        "**We hand it back clean**, with the invoice and the [[garantia-de-reparacion|repair warranty]].",
      ]),
      ("h2", "If you have had an accident"),
      ("p", "A crash is never pleasant. If another vehicle was involved, fill in the [[parte-amistoso|accident report form]] carefully and call us. We help you with the next steps: opening the claim, the assessor's visit and the repair. There is more information on our [claims](siniestros.html) page and in our [guide on what to do after an accident](guia-que-hacer-tras-un-accidente.html)."),
      ("p", "Remember that you can choose any workshop you like to repair your car. This is known as [[libre-eleccion-de-taller|free choice of repairer]], and your insurer cannot force you to go to a particular one. We explain it in our [guide to free choice of repairer](guia-libre-eleccion-de-taller.html)."),
      ("h2", "If you would rather pay yourself"),
      ("p", "Sometimes it is not worth making a claim: a small scrape, a car-park scratch or an [[franquicia|excess]] that is not worth using. In those cases we give you a [free, no-obligation estimate](presupuesto.html) and you decide calmly. If you just want to bring back the shine or improve the look, we can also polish the paint or restore the headlights."),
      ("p", "Whether your insurer pays or you do, the work is the same: we repair with the same care, use eco-friendly «eco-balance» paint and give you the same warranty. And if your insurer covers the repair, we coordinate with them so you do not have to act as go-between."),
      ("h2", "Made for the south of Tenerife"),
      ("p", "We are in Las Chafiras, on the Llano del Camello industrial estate, very close to the TF-1. We look after people from all over the south, foreign residents and those who spend part of the year here. Our hours are Monday to Friday, 07:00 to 16:00. If it is not easy for you to come in, ask us about collection and delivery. To get started, [request an appointment](pedir-cita.html) or drop us a message."),
    ],
    "faq": [
      ("Do I have to use the workshop my insurer suggests?", "No. You have the right to choose your repairer. If you choose us, we coordinate with your insurer and the loss adjuster."),
      ("Will you give me an estimate before repairing?", "Yes, always in writing and before we start. We do no work without your approval."),
      ("Do you have courtesy cars?", "It depends on availability and what your policy covers. We confirm it when we arrange the repair."),
      ("What does the lifetime paint warranty cover?", "It covers the paintwork we carry out, under the conditions we give you in writing when we hand the car back."),
      ("Can I be served in English?", "Yes, we look after many foreign residents and visitors. Message us and we will get back to you."),
    ],
  },
},
# ---------------------------------------------------------------------------
{
  "slug": "empresas-y-flotas", "cat": "clientes", "icon": "truck",
  "es": {
    "titulo": "Empresas y flotas",
    "corto": "Chapa y pintura para flotas, furgonetas, renting y rent a car del sur de Tenerife, con un interlocutor y el mínimo tiempo parado.",
    "entradilla": "Para una empresa, un vehículo en el taller es un vehículo que no trabaja. Organizamos la reparación de chapa y pintura de tu [[flota|flota]] para que vuelva a la carretera cuanto antes y con buena imagen.",
    "por_que_titulo": "Por qué trabajar con nosotros",
    "por_que": [
      ("clock", "Menos tiempo parado", "Planificamos los trabajos contigo para reducir al mínimo el tiempo que cada vehículo pasa inmovilizado."),
      ("users", "Un solo interlocutor", "Una persona de contacto que conoce tus vehículos y tus prioridades, sin repetir las cosas cada vez."),
      ("award", "Tu imagen, cuidada", "Tus vehículos son tu tarjeta de presentación. Los dejamos con la chapa y la pintura en buen estado."),
    ],
    "incluye_titulo": "Qué ofrecemos a empresas",
    "incluye_intro": "Adaptamos la forma de trabajar al tamaño de tu flota y a tu actividad.",
    "incluye": [
      ("truck", "Comerciales y furgonetas", "Reparación de golpes, roces y pintura en vehículos de trabajo y de reparto."),
      ("key", "Renting y devoluciones", "Reparamos los daños antes de devolver un vehículo de [[renting|renting]], para evitar cargos por desperfectos."),
      ("car", "Rent a car", "Puesta a punto de carrocería entre temporadas y reparación de los golpes típicos del alquiler."),
      ("calendar", "Planificación de trabajos", "Organizamos las entradas por turnos para que no se paren varios vehículos a la vez."),
      ("home", "Recogida y entrega", "Recogemos y entregamos los vehículos en tus instalaciones, según zona y disponibilidad."),
      ("doc", "Facturación a la empresa", "Presupuestos por escrito y facturas a nombre de la empresa, vehículo a vehículo."),
    ],
    "nota": "Las condiciones de trabajo, los plazos y la forma de facturar dependen de cada empresa y de cada reparación. Lo hablamos contigo y te lo confirmamos por escrito.",
    "texto": [
      ("h2", "Flotas de empresa y vehículos comerciales"),
      ("p", "Furgonetas de reparto, vehículos de técnicos, coches comerciales: todos acumulan roces, golpes de aparcamiento y arañazos. Si se dejan pasar, la imagen de la empresa se resiente y algunos daños pequeños acaban siendo más caros de reparar. Te ayudamos a mantener la flota presentable con reparaciones planificadas, sin esperar a que los pequeños daños se acumulen."),
      ("p", "Podemos revisar los vehículos que nos indiques, darte un presupuesto por vehículo y organizar las reparaciones según tus prioridades. Si hay rotulación, lo tenemos en cuenta al planificar el trabajo de pintura."),
      ("p", "También nos puedes traer los vehículos que han sufrido un golpe en ruta. Si el daño afecta a la estructura, contamos con [[bancada|bancada]] para repararla según las especificaciones del fabricante, y te explicamos con claridad qué se ha hecho para que tengas el historial de cada vehículo en orden."),
      ("h2", "Renting: antes de devolver el vehículo"),
      ("p", "Al final de un contrato de renting, la compañía revisa el vehículo y puede cobrar los daños que considere fuera del desgaste normal. Revisar la carrocería antes de la devolución te permite saber qué se va a ver y decidir qué reparar. Te damos [presupuesto](presupuesto.html) por escrito para que compares con lo que te podrían cobrar."),
      ("h2", "Rent a car del sur de Tenerife"),
      ("p", "En el sur de la isla hay mucho coche de alquiler y los daños se repiten: esquinas de paragolpes, retrovisores, arañazos en puertas y faros castigados por el sol. Conocemos este tipo de trabajo y nos adaptamos a los ritmos de la temporada. Podemos planificar reparaciones fuera de los picos y preparar la carrocería antes de que los coches vuelvan a salir."),
      ("h2", "Cómo lo organizamos"),
      ("checks", [
        "Una reunión o llamada para conocer tu flota, tus plazos y tu forma de trabajar.",
        "Una persona de contacto en el taller para todas tus reparaciones.",
        "Presupuesto por escrito antes de cada trabajo.",
        "Información del [estado en tiempo real](servicio-estado-en-tiempo-real.html) de cada vehículo.",
        "[Recogida y entrega](servicio-recogida-y-entrega.html) cuando es posible.",
        "Si el daño viene de un [[siniestro|siniestro]], nos coordinamos con la aseguradora.",
      ]),
      ("p", "Cuéntanos cuántos vehículos tienes y qué necesitas. [Contacta con nosotros](contacto.html) y vemos juntos la mejor forma de trabajar."),
    ],
    "faq": [
      ("¿Tenéis tarifas especiales para empresas?", "Cada flota es distinta. Lo hablamos contigo según el volumen y el tipo de trabajo, y te lo dejamos por escrito."),
      ("¿Podéis reparar furgonetas?", "Sí, reparamos la chapa y la pintura de turismos y vehículos comerciales. Si tienes un vehículo especial, consúltanos antes."),
      ("¿Me ayudáis antes de devolver un coche de renting?", "Sí. Revisamos la carrocería, te decimos qué se va a notar en la devolución y te damos presupuesto para repararlo."),
      ("¿Podéis facturar a nombre de la empresa?", "Sí, los presupuestos y las facturas van a nombre de la empresa, con el detalle de cada vehículo."),
      ("¿Recogéis los vehículos en nuestras instalaciones?", "Sí, cuando la zona y la disponibilidad lo permiten. Lo organizamos contigo."),
    ],
  },
  "en": {
    "titulo": "Businesses and fleets",
    "corto": "Bodywork and paint for fleets, vans, leasing and rent-a-car firms in south Tenerife, with one contact and minimum downtime.",
    "entradilla": "For a business, a vehicle in the workshop is a vehicle that is not working. We organise bodywork and paint repairs for your [[flota|fleet]] so it gets back on the road as soon as possible, looking good.",
    "por_que_titulo": "Why work with us",
    "por_que": [
      ("clock", "Less downtime", "We plan the work with you to keep the time each vehicle spends off the road to a minimum."),
      ("users", "One point of contact", "One person who knows your vehicles and your priorities, so you do not have to repeat yourself."),
      ("award", "Your image, looked after", "Your vehicles are your calling card. We keep their bodywork and paint in good shape."),
    ],
    "incluye_titulo": "What we offer businesses",
    "incluye_intro": "We adapt the way we work to the size of your fleet and your line of business.",
    "incluye": [
      ("truck", "Commercial vehicles and vans", "Repairs to dents, scrapes and paint on work and delivery vehicles."),
      ("key", "Leasing returns", "We repair damage before a [[renting|leased]] vehicle goes back, to avoid damage charges."),
      ("car", "Rent-a-car", "Bodywork preparation between seasons and repair of the typical dents and scrapes of rental cars."),
      ("calendar", "Work planning", "We stagger drop-offs so several vehicles are not off the road at the same time."),
      ("home", "Collection and delivery", "We collect and return vehicles at your premises, depending on the area and availability."),
      ("doc", "Invoicing to the company", "Written estimates and invoices in the company's name, vehicle by vehicle."),
    ],
    "nota": "Working terms, timings and invoicing depend on each business and each repair. We discuss it with you and confirm it in writing.",
    "texto": [
      ("h2", "Company fleets and commercial vehicles"),
      ("p", "Delivery vans, technicians' vehicles, sales cars: they all pick up scrapes, parking dents and scratches. If they are left, the company's image suffers and some small damage ends up costing more to fix. We help you keep your fleet presentable with planned repairs, without waiting for small damage to pile up."),
      ("p", "We can inspect the vehicles you point us to, give you an estimate per vehicle and organise the repairs according to your priorities. If your vehicles carry signwriting or livery, we take that into account when planning the paintwork."),
      ("p", "You can also bring us vehicles that have had a knock on the road. If the damage affects the structure, we have a [[bancada|chassis jig]] to repair it to the manufacturer's specifications, and we explain clearly what has been done so you keep each vehicle's history in order."),
      ("h2", "Leasing: before you hand the vehicle back"),
      ("p", "At the end of a leasing contract, the leasing company inspects the vehicle and may charge for damage it considers beyond normal wear and tear. Checking the bodywork before the return lets you know what they will see and decide what to repair. We give you a written [estimate](presupuesto.html) so you can compare it with what you might be charged."),
      ("h2", "Rent-a-car firms in the south of Tenerife"),
      ("p", "There are a lot of rental cars in the south of the island and the damage tends to repeat itself: bumper corners, mirrors, scratched doors and headlights worn by the sun. We know this kind of work and adapt to the rhythm of the season. We can plan repairs outside peak times and prepare the bodywork before the cars go back out."),
      ("h2", "How we organise it"),
      ("checks", [
        "A meeting or call to get to know your fleet, your timings and the way you work.",
        "One contact person at the workshop for all your repairs.",
        "A written estimate before every job.",
        "[Real-time status](servicio-estado-en-tiempo-real.html) updates for each vehicle.",
        "[Collection and delivery](servicio-recogida-y-entrega.html) where possible.",
        "If the damage comes from a [[siniestro|claim event]], we coordinate with the insurer.",
      ]),
      ("p", "Tell us how many vehicles you have and what you need. [Get in touch](contacto.html) and we will work out the best way to work together."),
    ],
    "faq": [
      ("Do you have special rates for businesses?", "Every fleet is different. We discuss it with you based on volume and type of work, and put it in writing."),
      ("Can you repair vans?", "Yes, we repair the bodywork and paint of cars and commercial vehicles. If you have a special vehicle, ask us first."),
      ("Can you help before I return a leased car?", "Yes. We check the bodywork, tell you what is likely to be noticed at the return and quote for repairing it."),
      ("Can you invoice the company?", "Yes, estimates and invoices are in the company's name, with details for each vehicle."),
      ("Do you collect vehicles from our premises?", "Yes, when the area and availability allow. We arrange it with you."),
    ],
  },
},
# ---------------------------------------------------------------------------
{
  "slug": "aseguradoras", "cat": "clientes", "icon": "shield",
  "es": {
    "titulo": "Aseguradoras, peritos y mediadores",
    "corto": "Reparamos los siniestros de vuestros asegurados en el sur de Tenerife, coordinados con el perito y con información clara en cada fase.",
    "entradilla": "Si eres una compañía de seguros, un perito o un mediador, somos un taller de chapa y pintura del sur de Tenerife preparado para reparar los [[siniestro|siniestros]] de tus asegurados con rigor y buena atención.",
    "por_que_titulo": "Por qué contar con nosotros",
    "por_que": [
      ("layers", "Reparación según fabricante", "Disponemos de [[bancada|bancada]] y del equipamiento necesario para trabajar con los estándares que exigen todas las marcas."),
      ("camera", "Coordinación con el perito", "Fotos, desmontajes cuando hace falta y valoración ordenada para que la peritación sea ágil."),
      ("users", "Buena atención al asegurado", "Tratamos a tu asegurado como a un cliente nuestro y le entregamos el coche limpio, por dentro y por fuera."),
    ],
    "incluye_titulo": "Cómo trabajamos los siniestros",
    "incluye_intro": "Un proceso claro, pensado para que la compañía, el perito y el asegurado sepan en todo momento en qué punto está la reparación.",
    "incluye": [
      ("clipboard", "Recepción y documentación", "Recibimos el vehículo, dejamos constancia de su estado y recopilamos los datos del siniestro."),
      ("camera", "Fotos y valoración", "Preparamos fotos y valoración de los daños para el [[perito|perito]], conforme al [[baremo|baremo]]."),
      ("hammer", "Reparación de chapa y estructura", "Reparación en bancada cuando el daño lo requiere, respetando las especificaciones del fabricante."),
      ("spray", "Pintura", "Pintura ecológica con igualación de color y garantía vitalicia en los trabajos de pintura."),
      ("eye", "Información de estado", "Información del estado de la reparación en tiempo real, para la compañía y para el asegurado."),
      ("sparkle", "Entrega", "Entregamos el vehículo limpio y explicamos al asegurado lo que se ha hecho."),
    ],
    "nota": "La forma de colaborar depende de cada compañía y de cada siniestro. Si quieres trabajar con nosotros, hablamos y te explicamos cómo nos organizamos.",
    "texto": [
      ("h2", "Para compañías de seguros y mediadores"),
      ("p", "Estamos en Las Chafiras, en pleno sur de Tenerife, con instalaciones amplias: taller de chapa, zona de pintura, almacén de recambios y bancadas. Podemos atender siniestros de chapa y pintura de turismos y vehículos comerciales, desde un golpe leve hasta daños que afectan a la estructura."),
      ("p", "Nos importa que la reparación quede bien y que el asegurado salga contento. Por eso cuidamos la información: sabe en qué fase está su coche, qué falta y cuándo se prevé la entrega. Eso reduce las llamadas a la compañía y mejora la experiencia de su cliente, que al final es también la imagen de la aseguradora."),
      ("p", "Si eres corredor o agente, puedes recomendarnos a tus clientes del sur de la isla con tranquilidad. Les damos un trato cercano, presupuesto claro, [recogida y entrega](servicio-recogida-y-entrega.html) cuando es posible y [vehículo de sustitución](servicio-vehiculo-de-sustitucion.html) según disponibilidad o póliza."),
      ("h2", "Para peritos"),
      ("p", "Facilitamos el trabajo de [[peritacion|peritación]]. Preparamos fotos de los daños, desmontamos cuando es necesario para ver daños ocultos y presentamos una valoración ordenada. Si durante la reparación aparece algo que no estaba previsto, lo documentamos con fotos y lo comunicamos antes de seguir, para acordar la ampliación."),
      ("p", "Cuando el daño es importante, revisamos también la estructura y, si hace falta, la reparamos en bancada con control de medidas. Si la reparación no fuese razonable en relación con el valor del vehículo, lo comunicamos cuanto antes para que la compañía y el perito valoren la situación con toda la información."),
      ("checks", [
        "Fotos de los daños antes, durante y después de la reparación.",
        "Valoración de mano de obra y materiales según baremo.",
        "Comunicación de daños ocultos antes de continuar.",
        "Reparación de estructura en bancada con control de medidas cuando el daño lo exige.",
      ]),
      ("h2", "Para el asegurado: tu libre elección de taller"),
      ("p", "Si eres el asegurado y has llegado hasta aquí: tienes derecho a la [[libre-eleccion-de-taller|libre elección de taller]]. Puedes pedir que tu coche se repare en Green Car Service aunque la compañía te sugiera otro taller. Nosotros nos coordinamos con tu aseguradora y con el perito. Te lo explicamos con detalle en la [guía de libre elección de taller](guia-libre-eleccion-de-taller.html) y en nuestra página de [gestión con aseguradoras](servicio-gestion-con-aseguradoras.html)."),
    ],
    "faq": [
      ("¿Con qué compañías trabajáis?", "Reparamos siniestros de asegurados de cualquier compañía que acepte la reparación en nuestro taller. Si representas a una aseguradora y quieres colaborar, hablemos."),
      ("¿Cómo se coordina la peritación?", "Preparamos fotos y valoración para el perito, facilitamos el acceso al vehículo y comunicamos cualquier daño oculto antes de seguir."),
      ("¿Reparáis daños estructurales?", "Sí. Contamos con bancada y el equipamiento necesario para reparar la estructura según las especificaciones del fabricante."),
      ("Soy asegurado, ¿puedo elegir vuestro taller?", "Sí. Tienes derecho a la libre elección de taller. Llámanos y te ayudamos a comunicarlo a tu compañía."),
    ],
  },
  "en": {
    "titulo": "Insurers, loss adjusters and brokers",
    "corto": "We repair your policyholders' claims in south Tenerife, coordinated with the loss adjuster and with clear updates at every stage.",
    "entradilla": "If you are an insurance company, a loss adjuster or a broker, we are a bodywork and paint shop in the south of Tenerife ready to repair your policyholders' [[siniestro|claims]] thoroughly and with good customer care.",
    "por_que_titulo": "Why work with us",
    "por_que": [
      ("layers", "Repairs to manufacturer standards", "We have a [[bancada|chassis jig]] and the equipment needed to work to the standards every manufacturer requires."),
      ("camera", "Coordination with the adjuster", "Photos, stripping down where needed and a clear assessment so the loss assessment runs smoothly."),
      ("users", "Good care of the policyholder", "We treat your policyholder as our own customer and return the car clean, inside and out."),
    ],
    "incluye_titulo": "How we handle claims",
    "incluye_intro": "A clear process, so the insurer, the adjuster and the policyholder always know where the repair stands.",
    "incluye": [
      ("clipboard", "Intake and paperwork", "We receive the vehicle, record its condition and gather the claim details."),
      ("camera", "Photos and assessment", "We prepare photos and a damage assessment for the [[perito|loss adjuster]], in line with the [[baremo|repair time schedule]]."),
      ("hammer", "Bodywork and structural repair", "Repairs on the jig when the damage requires it, following the manufacturer's specifications."),
      ("spray", "Paint", "Eco-friendly paint with colour matching and a lifetime warranty on paintwork."),
      ("eye", "Status updates", "Real-time information on the repair status for the insurer and the policyholder."),
      ("sparkle", "Handover", "We return the vehicle clean and explain to the policyholder what has been done."),
    ],
    "nota": "How we work together depends on each insurer and each claim. If you would like to work with us, let's talk and we will explain how we are organised.",
    "texto": [
      ("h2", "For insurance companies and brokers"),
      ("p", "We are in Las Chafiras, right in the south of Tenerife, with spacious premises: bodywork shop, paint area, parts store and chassis jigs. We can handle bodywork and paint claims for cars and commercial vehicles, from a light knock to damage that affects the structure."),
      ("p", "We care about the repair being done well and the policyholder leaving happy. That is why we pay attention to communication: they know what stage their car is at, what is left and when handover is expected. That means fewer calls to the insurer and a better experience for their customer."),
      ("p", "If you are a broker or agent, you can recommend us to your clients in the south of the island with confidence. We give them a personal service, a clear estimate, [collection and delivery](servicio-recogida-y-entrega.html) where possible and a [courtesy car](servicio-vehiculo-de-sustitucion.html) depending on availability or policy."),
      ("h2", "For loss adjusters"),
      ("p", "We make the [[peritacion|loss assessment]] easier. We prepare photos of the damage, strip down where needed to reveal hidden damage and present a clear assessment. If something unexpected appears during the repair, we document it with photos and report it before carrying on, so the supplement can be agreed."),
      ("p", "When the damage is significant, we also check the structure and, if needed, repair it on the jig with measurement checks. If the repair did not seem reasonable compared with the vehicle's value, we flag it as early as possible so the insurer and the adjuster can assess the situation with all the information."),
      ("checks", [
        "Photos of the damage before, during and after the repair.",
        "Labour and materials assessed according to the schedule.",
        "Hidden damage reported before continuing.",
        "Structural repair on the jig with measurement checks when the damage requires it.",
      ]),
      ("h2", "For policyholders: your free choice of repairer"),
      ("p", "If you are the policyholder and have landed here: you have the right to [[libre-eleccion-de-taller|free choice of repairer]]. You can ask for your car to be repaired at Green Car Service even if your insurer suggests another workshop. We coordinate with your insurer and the loss adjuster. We explain it in detail in our [guide to free choice of repairer](guia-libre-eleccion-de-taller.html) and on our [dealing with insurers](servicio-gestion-con-aseguradoras.html) page."),
    ],
    "faq": [
      ("Which insurers do you work with?", "We repair claims for policyholders of any insurer that accepts the repair at our workshop. If you represent an insurer and would like to work together, let's talk."),
      ("How is the loss assessment coordinated?", "We prepare photos and an assessment for the adjuster, give access to the vehicle and report any hidden damage before continuing."),
      ("Do you repair structural damage?", "Yes. We have a chassis jig and the equipment needed to repair the structure to the manufacturer's specifications."),
      ("I am a policyholder. Can I choose your workshop?", "Yes. You have the right to free choice of repairer. Call us and we will help you tell your insurer."),
    ],
  },
},
]
