"""Fichas de revisión para compraventa (ES/EN)."""

SERVICIOS = [
# ---------------------------------------------------------------------------
{
  "slug": "revision-antes-de-comprar", "cat": "revision", "icon": "search",
  "es": {
    "titulo": "Revisión antes de comprar",
    "corto": "Antes de pagar, revisamos la carrocería, la pintura, la estructura y los papeles del coche que te interesa.",
    "entradilla": "Un coche de segunda mano puede verse impecable en las fotos y esconder un golpe fuerte mal reparado. Lo revisamos con ojos de taller de chapa y pintura para que compres sabiendo lo que compras.",
    "por_que_titulo": "Por qué revisarlo antes de comprar",
    "por_que": [
      ("eye", "Lo que no se ve a simple vista", "Una reparación de chapa bien disimulada puede pasar desapercibida para cualquiera. Nosotros reparamos carrocerías a diario y sabemos dónde mirar."),
      ("euro", "Argumentos para negociar", "Si aparecen reparaciones o daños, tienes datos concretos y fotos para hablar del precio con el vendedor, o para decidir no seguir."),
      ("shield", "Compras con tranquilidad", "Sabes si la estructura del coche ha sufrido un impacto importante y si la documentación está en regla antes de firmar nada."),
    ],
    "incluye_titulo": "Qué revisamos",
    "incluye_intro": "Nos centramos en lo que conocemos a fondo: carrocería, pintura, estructura y documentación.",
    "incluye": [
      ("layers", "Pintura pieza a pieza", "Medimos cada panel con [[medidor-de-espesores|medidor de espesores]] para detectar piezas repintadas, masilla o capas añadidas."),
      ("hammer", "Carrocería y estructura", "Holguras entre piezas, soldaduras no originales, [[sellador|sellados]] distintos a los de fábrica y señales de golpes en largueros y refuerzos."),
      ("light", "Lunas, faros y plásticos", "Impactos y marcas en lunas, faros opacos o sustituidos, paragolpes y molduras con daños o reparaciones."),
      ("drop", "Bajos, corrosión e interior", "Óxido en bajos y zonas ocultas, algo habitual con el salitre de la costa, y humedades o desgaste en el habitáculo."),
      ("doc", "Documentación", "Revisamos contigo el [[informe-dgt|informe de la DGT]], la [[itv|ITV]] vigente, las cargas y la titularidad."),
      ("camera", "Informe con fotos", "Al terminar te lo explicamos y te entregamos un informe con fotos de lo que hemos encontrado."),
    ],
    "nota": "Nuestra revisión se centra en carrocería, pintura, estructura y documentación. Es una valoración del estado del coche en el momento de verlo, no una garantía sobre su futuro.",
    "texto": [
      ("h2", "Cómo funciona"),
      ("p", "El proceso es sencillo y lo adaptamos a cada caso. La idea es que tú no tengas que ser experto en coches para tomar una buena decisión."),
      ("checks", [
        "**Nos dices qué coche y dónde está.** Marca, modelo, matrícula si la tienes y si lo vende un particular o un profesional.",
        "**Lo traes al taller o lo acordamos con el vendedor.** Lo ideal es verlo en nuestras instalaciones de Las Chafiras, con buena luz y elevador.",
        "**Hacemos la revisión.** Recorremos el coche panel a panel, por fuera, por debajo y por dentro.",
        "**Te lo explicamos al terminar.** Te contamos lo que hemos visto y qué importancia tiene cada cosa.",
        "**Te entregamos el informe con fotos.** Para que decidas con calma y, si sigues adelante, negocies con datos.",
      ]),
      ("h2", "Señales de reparaciones previas que buscamos"),
      ("p", "Un coche que ha pasado por chapa y pintura no es necesariamente un mal coche. Lo importante es saber qué se reparó y cómo. Estas son algunas de las pistas que revisamos:"),
      ("checks", [
        "Diferencias de grosor de pintura entre piezas vecinas, medidas con aparato y no a ojo.",
        "Diferencias de tono entre puertas, aletas o paragolpes, que a veces solo se ven con luz rasante.",
        "Textura de [[piel-de-naranja|piel de naranja]] distinta a la del resto del coche, o motas y descolgados.",
        "Restos de pintura en gomas, juntas, cristales o plásticos que indican un pintado sin desmontar.",
        "Holguras desiguales entre capó, puertas y portón.",
        "Soldaduras y sellados que no son los de fábrica en vanos, maletero o pasos de rueda.",
        "Tornillos de aletas o bisagras con marcas de haber sido manipulados.",
      ]),
      ("h2", "Tenerife tiene sus particularidades"),
      ("p", "En el sur de la isla el sol castiga barnices y faros, y el ambiente marino favorece la [[corrosion|corrosión]] en bajos, anclajes y rincones donde se acumula la humedad. También circulan muchos coches que han sido de alquiler, con kilómetros de ciudad y de carretera de montaña. Por eso miramos con atención los bajos y la parte baja de las puertas, además del estado real de la pintura."),
      ("p", "Si estás empezando a buscar, te recomendamos leer nuestra [guía para comprar un coche de ocasión](guia-comprar-coche-de-ocasion.html). Y si prefieres ver coches que ya conocemos, echa un vistazo a nuestros [coches de ocasión](coches-de-ocasion.html)."),
      ("h2", "Qué hacer con el resultado"),
      ("p", "Con el informe en la mano puedes comprar tranquilo, negociar el precio teniendo en cuenta lo que hay que reparar o descartar el coche. Si decides comprarlo y hay algo que arreglar, te podemos hacer un [presupuesto](presupuesto.html) de la reparación para que sepas cuánto supone antes de cerrar el trato. Para reservar la revisión, [pide cita](pedir-cita.html) o escríbenos por WhatsApp."),
    ],
    "faq": [
      ("¿En qué partes del coche se centra la revisión?", "En carrocería, pintura, estructura y documentación. Somos un taller de chapa y pintura y es lo que conocemos a fondo."),
      ("¿Tengo que llevar el coche al taller?", "Es lo más recomendable, porque aquí tenemos luz, elevador y herramientas. Si no es posible, lo hablamos y vemos la mejor forma de organizarlo con el vendedor."),
      ("¿Cuánto cuesta la revisión?", "Depende del tipo de coche y de dónde esté. Pregúntanos y te confirmamos el precio antes de hacer nada."),
      ("¿El vendedor tiene que estar de acuerdo?", "Sí, necesitamos acceso al coche. Un vendedor que no tiene nada que ocultar suele aceptar sin problema, y si se niega, eso también es información."),
      ("¿Me podéis reparar lo que encontréis?", "Sí. Si compras el coche, podemos darte presupuesto de cualquier reparación de chapa y pintura que haya salido en la revisión."),
    ],
  },
  "en": {
    "titulo": "Pre-purchase inspection",
    "corto": "Before you pay, we check the bodywork, paint, structure and paperwork of the car you are interested in.",
    "entradilla": "A used car can look spotless in photos and still hide a badly repaired heavy impact. We inspect it with the eyes of a bodywork and paint shop, so you know exactly what you are buying.",
    "por_que_titulo": "Why inspect before you buy",
    "por_que": [
      ("eye", "What you cannot see at a glance", "A well-disguised body repair can fool almost anyone. We repair bodywork every day and know where to look."),
      ("euro", "Arguments to negotiate", "If repairs or damage turn up, you have specific facts and photos to discuss the price with the seller, or to walk away."),
      ("shield", "Buy with peace of mind", "You find out whether the car's structure has taken a serious hit and whether the paperwork is in order before you sign anything."),
    ],
    "incluye_titulo": "What we check",
    "incluye_intro": "We focus on what we know inside out: bodywork, paint, structure and paperwork.",
    "incluye": [
      ("layers", "Paint, panel by panel", "We measure every panel with a [[medidor-de-espesores|paint thickness gauge]] to spot resprayed parts, filler or extra layers."),
      ("hammer", "Bodywork and structure", "Panel gaps, non-factory welds, [[sellador|seam sealer]] that differs from the original and signs of impacts on chassis rails and reinforcements."),
      ("light", "Glass, headlights and plastics", "Chips and marks on the glass, cloudy or replaced headlights, bumpers and trims with damage or repairs."),
      ("drop", "Underbody, rust and interior", "Rust on the underbody and hidden areas, common with coastal salt air, plus damp or wear inside the cabin."),
      ("doc", "Paperwork", "We go through the [[informe-dgt|DGT vehicle report]], a valid [[itv|ITV]], any charges on the car and ownership with you."),
      ("camera", "Report with photos", "When we finish we talk you through it and give you a report with photos of what we found."),
    ],
    "nota": "Our inspection focuses on bodywork, paint, structure and paperwork. It is an assessment of the car's condition on the day we see it, not a guarantee about its future.",
    "texto": [
      ("h2", "How it works"),
      ("p", "The process is simple and we adapt it to each case. The idea is that you do not need to be a car expert to make a good decision."),
      ("checks", [
        "**Tell us which car and where it is.** Make, model, registration if you have it, and whether it is sold privately or by a dealer.",
        "**Bring it in or we arrange it with the seller.** Ideally we see it at our premises in Las Chafiras, with good light and a lift.",
        "**We carry out the inspection.** We go round the car panel by panel, outside, underneath and inside.",
        "**We explain it when we finish.** We tell you what we have seen and how much each point matters.",
        "**You get the report with photos.** So you can decide calmly and, if you go ahead, negotiate with facts.",
      ]),
      ("h2", "Signs of previous repairs we look for"),
      ("p", "A car that has been through a body shop is not necessarily a bad car. What matters is knowing what was repaired and how. These are some of the clues we check:"),
      ("checks", [
        "Differences in paint thickness between neighbouring panels, measured with a gauge rather than by eye.",
        "Differences in shade between doors, wings or bumpers, sometimes only visible under low-angle light.",
        "[[piel-de-naranja|Orange peel]] texture that differs from the rest of the car, or specks and runs.",
        "Paint overspray on rubber seals, trims, glass or plastics, a sign it was painted without removing parts.",
        "Uneven gaps around the bonnet, doors and tailgate.",
        "Welds and sealer that are not factory-made in door openings, the boot or wheel arches.",
        "Wing or hinge bolts showing marks from having been undone.",
      ]),
      ("h2", "Tenerife has its own quirks"),
      ("p", "In the south of the island the sun is hard on clear coat and headlights, and the sea air encourages [[corrosion|corrosion]] on the underbody, mounting points and corners where moisture collects. There are also plenty of ex-rental cars around, with a mix of town driving and mountain roads. That is why we pay close attention to the underbody and the lower edges of the doors, as well as the real condition of the paint."),
      ("p", "If you are just starting your search, have a look at our [guide to buying a used car](guia-comprar-coche-de-ocasion.html). And if you would rather see cars we already know, browse our [used cars](coches-de-ocasion.html)."),
      ("h2", "What to do with the result"),
      ("p", "With the report in hand you can buy with confidence, negotiate the price taking into account what needs fixing, or rule the car out. If you decide to buy it and something needs repairing, we can give you an [estimate](presupuesto.html) for the work so you know the cost before closing the deal. To book the inspection, [request an appointment](pedir-cita.html) or message us on WhatsApp."),
    ],
    "faq": [
      ("What does the inspection focus on?", "Bodywork, paint, structure and paperwork. We are a bodywork and paint shop, and that is what we know inside out."),
      ("Do I have to bring the car to your workshop?", "It is the best option, because here we have the light, the lift and the tools. If that is not possible, we talk it through and find the best way to arrange it with the seller."),
      ("How much does the inspection cost?", "It depends on the type of car and where it is. Ask us and we will confirm the price before doing anything."),
      ("Does the seller have to agree?", "Yes, we need access to the car. A seller with nothing to hide usually agrees without fuss, and if they refuse, that tells you something too."),
      ("Can you repair what you find?", "Yes. If you buy the car, we can quote for any bodywork or paint repair that came up in the inspection."),
    ],
  },
},
# ---------------------------------------------------------------------------
{
  "slug": "revision-antes-de-vender", "cat": "revision", "icon": "handshake",
  "es": {
    "titulo": "Revisión antes de vender",
    "corto": "Revisamos tu coche antes de ponerlo a la venta para que sepas cómo está y puedas enseñarlo con transparencia.",
    "entradilla": "Vender un coche es más fácil cuando el comprador confía. Revisamos la carrocería, la pintura, la estructura y los papeles de tu coche y te damos un informe que puedes enseñar.",
    "por_que_titulo": "Por qué revisarlo antes de venderlo",
    "por_que": [
      ("handshake", "Das confianza", "Un informe de un taller de chapa y pintura responde de antemano a muchas de las dudas del comprador."),
      ("search", "Sin sorpresas al negociar", "Sabes lo que el comprador puede encontrar si lo revisa, y puedes fijar el precio con realismo."),
      ("clipboard", "Decides qué arreglar", "Te decimos qué merece la pena reparar antes de vender y qué es mejor dejar tal cual y explicar."),
    ],
    "incluye_titulo": "Qué incluye",
    "incluye_intro": "Es la misma revisión que hacemos a quien va a comprar, pero pensada para ti como vendedor.",
    "incluye": [
      ("layers", "Pintura medida", "Medimos todos los paneles con [[medidor-de-espesores|medidor de espesores]] y anotamos lo que es original y lo que no."),
      ("hammer", "Carrocería y estructura", "Revisamos golpes, holguras, soldaduras y señales de reparaciones anteriores, también las que quizá no conocías."),
      ("light", "Lunas, faros y plásticos", "Anotamos impactos, faros amarillentos y paragolpes rozados que el comprador va a ver."),
      ("drop", "Bajos e interior", "Miramos la [[corrosion|corrosión]] en los bajos y el estado estético del habitáculo."),
      ("doc", "Papeles en orden", "Te recordamos qué revisar: [[informe-dgt|informe de la DGT]], [[itv|ITV]] vigente, cargas y titularidad."),
      ("camera", "Informe para enseñar", "Te entregamos un informe con fotos que puedes mostrar a los interesados."),
    ],
    "nota": "El informe describe el estado real del coche, incluidas las reparaciones previas que encontremos. No ocultamos nada: precisamente eso es lo que le da valor ante el comprador.",
    "texto": [
      ("h2", "Cómo funciona"),
      ("checks", [
        "**Nos cuentas qué coche vendes** y en qué momento estás: si ya lo tienes anunciado o aún no.",
        "**Lo traes al taller** o lo organizamos con recogida si te viene mejor y es posible.",
        "**Lo revisamos** por fuera, por debajo y por dentro, con medidor de pintura y buena luz.",
        "**Te lo explicamos al terminar**: qué está bien, qué se nota y qué conviene arreglar.",
        "**Te entregamos el informe con fotos**, listo para enseñar a los compradores.",
      ]),
      ("h2", "La transparencia vende"),
      ("p", "Muchos compradores llegan con desconfianza, sobre todo si han leído historias de coches con golpes ocultos. Cuando les enseñas un informe hecho por un taller de chapa y pintura, con fotos y medidas de pintura, la conversación cambia. Ya no discutís sobre sospechas, sino sobre hechos."),
      ("p", "Si tu coche tuvo un golpe y se reparó bien, el informe lo refleja. Eso suele tranquilizar más que decir que nunca ha tenido nada. Y si hay algo que no está bien reparado, es mejor que lo sepas tú antes que que lo descubra el comprador en plena negociación."),
      ("p", "La revisión también te ayuda con los papeles. Antes de vender conviene tener a mano el [[informe-dgt|informe de la DGT]] del coche, comprobar que la [[itv|ITV]] está vigente y que no hay cargas pendientes. Son las primeras cosas que un comprador informado va a pedir, y tenerlas preparadas da una imagen seria."),
      ("h2", "Qué suele merecer la pena arreglar"),
      ("p", "No siempre compensa reparar todo antes de vender. Te damos nuestra opinión sincera, caso por caso. Lo que más suele ayudar es lo que se ve en las fotos del anuncio y en los primeros minutos de visita:"),
      ("checks", [
        "Pintura apagada o con marcas de lavado: un [pulido y abrillantado](servicio-pulido-y-abrillantado.html) cambia mucho la primera impresión.",
        "Faros amarillentos: la [restauración de faros](servicio-restauracion-de-faros.html) mejora el aspecto y la visibilidad.",
        "Pequeños golpes en puertas o aletas: muchas veces tienen [arreglo sencillo](servicio-golpes-y-abolladuras.html).",
        "Arañazos en paragolpes y retoques de pintura en zonas visibles.",
      ]),
      ("p", "Si quieres dejarlo todo listo, mira nuestra [puesta a punto para vender](puesta-a-punto-para-vender.html). Y antes de cualquier trabajo te damos [presupuesto](presupuesto.html) por escrito para que decidas."),
      ("h2", "Reserva la revisión"),
      ("p", "Lo ideal es hacer la revisión antes de publicar el anuncio, así puedes incluir el informe desde el principio. [Pide cita](pedir-cita.html) o escríbenos por WhatsApp y lo organizamos."),
    ],
    "faq": [
      ("¿El informe dirá que mi coche tuvo un golpe?", "Si encontramos una reparación previa, sí. El informe es honesto; si la reparación está bien hecha, también lo diremos."),
      ("¿Tengo que arreglar lo que encontréis?", "No. Tú decides. Te decimos qué creemos que compensa y qué no, y te damos presupuesto de lo que quieras."),
      ("¿Sirve el informe si vendo a un concesionario?", "Puede ayudarte a saber el estado real de tu coche antes de que lo tasen, pero cada comprador hace su propia valoración."),
      ("¿Cuánto cuesta?", "Depende del coche. Te confirmamos el precio antes de hacer la revisión."),
    ],
  },
  "en": {
    "titulo": "Pre-sale inspection",
    "corto": "We inspect your car before you put it up for sale, so you know its condition and can show it with full transparency.",
    "entradilla": "Selling a car is easier when the buyer trusts you. We check your car's bodywork, paint, structure and paperwork and give you a report you can show.",
    "por_que_titulo": "Why inspect before you sell",
    "por_que": [
      ("handshake", "You build trust", "A report from a bodywork and paint shop answers many of the buyer's questions before they ask."),
      ("search", "No surprises when negotiating", "You know what a buyer could find if they have it checked, and you can set a realistic price."),
      ("clipboard", "You choose what to fix", "We tell you what is worth repairing before selling and what is better left as it is and explained."),
    ],
    "incluye_titulo": "What it includes",
    "incluye_intro": "It is the same inspection we carry out for buyers, but designed for you as the seller.",
    "incluye": [
      ("layers", "Measured paint", "We measure every panel with a [[medidor-de-espesores|paint thickness gauge]] and note what is original and what is not."),
      ("hammer", "Bodywork and structure", "We check dents, panel gaps, welds and signs of earlier repairs, including ones you may not know about."),
      ("light", "Glass, headlights and plastics", "We note chips, yellowed headlights and scuffed bumpers the buyer is going to notice."),
      ("drop", "Underbody and interior", "We look for [[corrosion|corrosion]] underneath and at the cosmetic condition of the cabin."),
      ("doc", "Paperwork in order", "We remind you what to check: the [[informe-dgt|DGT vehicle report]], a valid [[itv|ITV]], charges and ownership."),
      ("camera", "A report you can show", "You get a report with photos you can share with interested buyers."),
    ],
    "nota": "The report describes the car's real condition, including any earlier repairs we find. We do not hide anything: that is exactly what gives it value in the buyer's eyes.",
    "texto": [
      ("h2", "How it works"),
      ("checks", [
        "**Tell us which car you are selling** and where you are: already advertised or not yet.",
        "**Bring it in**, or we arrange collection if that suits you better and it is possible.",
        "**We inspect it** outside, underneath and inside, with a paint gauge and good light.",
        "**We explain it when we finish**: what is fine, what shows and what is worth fixing.",
        "**You get the report with photos**, ready to show buyers.",
      ]),
      ("h2", "Transparency sells"),
      ("p", "Many buyers turn up wary, especially if they have read stories about cars with hidden damage. When you show them a report from a bodywork and paint shop, with photos and paint readings, the conversation changes. You are no longer arguing about suspicions but talking about facts."),
      ("p", "If your car had a knock and it was repaired properly, the report shows that. That often reassures buyers more than claiming it has never had anything. And if something was not repaired well, it is better that you find out before the buyer does in the middle of negotiating."),
      ("p", "The inspection also helps with the paperwork. Before selling it is worth having the car's [[informe-dgt|DGT vehicle report]] to hand, checking the [[itv|ITV]] is valid and making sure there are no outstanding charges. These are the first things an informed buyer will ask for, and having them ready makes a serious impression."),
      ("h2", "What is usually worth fixing"),
      ("p", "It does not always pay to repair everything before selling. We give you our honest opinion, case by case. What helps most is what shows in the advert photos and in the first few minutes of a viewing:"),
      ("checks", [
        "Dull paint or wash marks: [polishing](servicio-pulido-y-abrillantado.html) makes a big difference to first impressions.",
        "Yellowed headlights: [headlight restoration](servicio-restauracion-de-faros.html) improves both looks and visibility.",
        "Small dents in doors or wings: they often have a [simple fix](servicio-golpes-y-abolladuras.html).",
        "Scratches on bumpers and paint touch-ups in visible areas.",
      ]),
      ("p", "If you want everything ready, have a look at our [pre-sale preparation](puesta-a-punto-para-vender.html). Before any work, we give you a written [estimate](presupuesto.html) so you can decide."),
      ("h2", "Book the inspection"),
      ("p", "Ideally, have it done before you publish the advert, so you can include the report from day one. [Request an appointment](pedir-cita.html) or message us on WhatsApp and we will arrange it."),
    ],
    "faq": [
      ("Will the report say my car had an accident?", "If we find an earlier repair, yes. The report is honest; if the repair was done well, we will say that too."),
      ("Do I have to fix what you find?", "No. It is your decision. We tell you what we think is worth it and what is not, and quote for whatever you want."),
      ("Is the report useful if I sell to a dealer?", "It can help you know your car's real condition before it is valued, but every buyer makes their own assessment."),
      ("How much does it cost?", "It depends on the car. We confirm the price before carrying out the inspection."),
    ],
  },
},
# ---------------------------------------------------------------------------
{
  "slug": "informe-de-carroceria-y-pintura", "cat": "revision", "icon": "clipboard",
  "es": {
    "titulo": "Informe de carrocería y pintura",
    "corto": "Un informe con fotos y medidas de pintura que describe el estado real de la carrocería, la estructura y la documentación.",
    "entradilla": "Es el documento que te entregamos tras revisar un coche, ya sea para comprarlo o para venderlo. Claro, con fotos y explicado en persona.",
    "por_que_titulo": "Para qué sirve el informe",
    "por_que": [
      ("check", "Para decidir", "Te ayuda a decidir si compras un coche, si lo vendes tal cual o si merece la pena repararlo antes."),
      ("euro", "Para negociar", "Las fotos y las medidas son argumentos concretos a la hora de hablar del precio."),
      ("handshake", "Para dar confianza", "Si vendes, el comprador ve el estado del coche descrito por un taller de chapa y pintura."),
    ],
    "incluye_titulo": "Qué recoge el informe",
    "incluye_intro": "Lo organizamos por zonas del coche para que sea fácil de leer, aunque no seas del oficio.",
    "incluye": [
      ("layers", "Mapa de pintura", "Medidas de [[medidor-de-espesores|espesor de pintura]] por panel, con las piezas que parecen repintadas o con masilla."),
      ("hammer", "Carrocería y estructura", "Golpes, holguras, soldaduras y [[sellador|sellados]] no originales, y cualquier señal de impacto en la estructura."),
      ("light", "Lunas, faros y plásticos", "Estado de parabrisas, lunas, faros, pilotos, paragolpes y molduras."),
      ("drop", "Bajos, corrosión e interior", "Óxido en bajos y zonas ocultas, humedades y estado estético del habitáculo."),
      ("doc", "Documentación", "Lo que hemos comprobado contigo: [[informe-dgt|informe de la DGT]], ITV, cargas y titularidad."),
      ("camera", "Fotos y conclusiones", "Fotos de cada punto relevante y un resumen con lo que consideramos importante y lo que es menor."),
    ],
    "nota": "El informe se limita a carrocería, pintura, estructura y documentación, y refleja el estado del coche el día de la revisión. No es una tasación ni una garantía.",
    "texto": [
      ("h2", "Un informe pensado para entenderse"),
      ("p", "Un listado de cifras no le sirve a nadie si no sabe interpretarlas. Por eso, además de entregarte el informe, te lo explicamos en persona o por teléfono al terminar la revisión. Te decimos qué significa cada hallazgo y qué importancia le damos."),
      ("p", "No es lo mismo un paragolpes repintado por un roce que una aleta con masilla gruesa o un larguero con soldaduras que no son de fábrica. El primero es algo normal en un coche con años; lo último merece mirarlo con calma. En el informe separamos lo menor de lo relevante."),
      ("h2", "Las medidas de pintura, explicadas"),
      ("p", "La pintura de fábrica tiene un grosor bastante uniforme en todo el coche. Cuando una pieza se ha repintado, o lleva [[masilla|masilla]] debajo, el grosor cambia. Con el medidor de espesores tomamos lecturas en varios puntos de cada panel y las comparamos entre sí."),
      ("p", "Una lectura alta no significa necesariamente un mal arreglo, pero sí que esa pieza ha pasado por el taller. Lo cruzamos con lo que vemos: tono, textura, [[piel-de-naranja|piel de naranja]], restos de pintura en gomas, holguras y tornillería. Así llegamos a conclusiones razonadas y no a suposiciones."),
      ("h2", "Estructura, bajos y documentación"),
      ("p", "Además de la pintura, el informe recoge lo que vemos en la estructura: si hay señales de que el coche ha pasado por [[bancada|bancada]], soldaduras que no son de fábrica en largueros o pasos de rueda, o sellados diferentes a los originales. También anotamos el estado de los bajos, donde el salitre del sur de Tenerife favorece la [[corrosion|corrosión]], y cualquier humedad en el interior. Por último, dejamos constancia de lo que hemos comprobado en la documentación, como la ITV vigente, las cargas y la titularidad, para que tengas toda la información en un mismo sitio."),
      ("h2", "Qué hacer con el informe"),
      ("checks", [
        "**Si compras:** úsalo para decidir y para negociar. Si hay algo que reparar, te podemos dar [presupuesto](presupuesto.html) antes de cerrar el trato.",
        "**Si vendes:** enséñalo a los interesados. Da confianza y evita discusiones.",
        "**Si ya es tuyo:** te sirve para saber cómo está tu coche y planificar reparaciones.",
      ]),
      ("p", "El informe forma parte de nuestra [revisión antes de comprar](revision-antes-de-comprar.html) y de la [revisión antes de vender](revision-antes-de-vender.html). Si te interesa, [pide cita](pedir-cita.html) y te contamos cómo organizarlo."),
    ],
    "faq": [
      ("¿En qué formato me dais el informe?", "Te lo entregamos por escrito con fotos, en un formato que puedas guardar y compartir fácilmente. Te confirmamos los detalles al pedir la revisión."),
      ("¿Incluye una tasación del coche?", "No. Describimos el estado de carrocería, pintura, estructura y documentación, pero no ponemos precio al coche."),
      ("¿Puedo enseñarlo a un comprador?", "Sí, está pensado también para eso. Refleja el estado del coche el día que lo revisamos."),
      ("¿Qué no recoge el informe?", "Todo lo que queda fuera de carrocería, pintura, estructura y documentación. Nos ceñimos a nuestra especialidad para que lo que te decimos sea fiable."),
    ],
  },
  "en": {
    "titulo": "Bodywork and paint report",
    "corto": "A report with photos and paint readings describing the real condition of the bodywork, structure and paperwork.",
    "entradilla": "It is the document we give you after inspecting a car, whether you are buying or selling. Clear, with photos, and explained in person.",
    "por_que_titulo": "What the report is for",
    "por_que": [
      ("check", "To decide", "It helps you decide whether to buy a car, sell it as it is or repair it first."),
      ("euro", "To negotiate", "Photos and readings are concrete arguments when you talk about the price."),
      ("handshake", "To build trust", "If you are selling, the buyer sees the car's condition described by a bodywork and paint shop."),
    ],
    "incluye_titulo": "What the report covers",
    "incluye_intro": "We organise it by area of the car so it is easy to read, even if you are not in the trade.",
    "incluye": [
      ("layers", "Paint map", "[[medidor-de-espesores|Paint thickness]] readings per panel, highlighting parts that seem resprayed or filled."),
      ("hammer", "Bodywork and structure", "Dents, panel gaps, non-factory welds and [[sellador|sealer]], and any sign of structural impact."),
      ("light", "Glass, headlights and plastics", "Condition of the windscreen, windows, headlights, rear lights, bumpers and trims."),
      ("drop", "Underbody, rust and interior", "Rust underneath and in hidden areas, damp and the cosmetic condition of the cabin."),
      ("doc", "Paperwork", "What we checked with you: the [[informe-dgt|DGT vehicle report]], ITV, charges and ownership."),
      ("camera", "Photos and conclusions", "Photos of each relevant point and a summary of what we consider important and what is minor."),
    ],
    "nota": "The report is limited to bodywork, paint, structure and paperwork, and reflects the car's condition on the day of the inspection. It is not a valuation or a guarantee.",
    "texto": [
      ("h2", "A report designed to be understood"),
      ("p", "A list of numbers is no use if you do not know how to read it. So as well as giving you the report, we explain it in person or by phone when we finish. We tell you what each finding means and how much weight we give it."),
      ("p", "A bumper resprayed after a scrape is not the same as a wing with thick filler or a chassis rail with non-factory welds. The first is normal on a car with a few years behind it; the last deserves a careful look. In the report we separate the minor from the relevant."),
      ("h2", "Paint readings, explained"),
      ("p", "Factory paint has a fairly even thickness across the whole car. When a panel has been resprayed, or has [[masilla|body filler]] underneath, the thickness changes. With the gauge we take readings at several points on each panel and compare them."),
      ("p", "A high reading does not necessarily mean a bad repair, but it does mean that panel has been in a body shop. We cross-check it with what we see: shade, texture, [[piel-de-naranja|orange peel]], overspray on seals, panel gaps and bolts. That way we reach reasoned conclusions rather than guesses."),
      ("h2", "Structure, underbody and paperwork"),
      ("p", "Beyond the paint, the report records what we see in the structure: signs that the car has been on a [[bancada|chassis jig]], non-factory welds on chassis rails or wheel arches, or sealer that differs from the original. We also note the condition of the underbody, where the salt air in the south of Tenerife encourages [[corrosion|corrosion]], and any damp inside the cabin. Finally, we record what we checked in the paperwork, such as a valid ITV, charges and ownership, so you have all the information in one place."),
      ("h2", "What to do with the report"),
      ("checks", [
        "**If you are buying:** use it to decide and to negotiate. If something needs fixing, we can give you an [estimate](presupuesto.html) before you close the deal.",
        "**If you are selling:** show it to interested buyers. It builds trust and avoids arguments.",
        "**If the car is already yours:** it tells you how your car is and helps you plan repairs.",
      ]),
      ("p", "The report is part of our [pre-purchase inspection](revision-antes-de-comprar.html) and our [pre-sale inspection](revision-antes-de-vender.html). If you are interested, [request an appointment](pedir-cita.html) and we will tell you how to arrange it."),
    ],
    "faq": [
      ("What format is the report in?", "We give it to you in writing with photos, in a format you can easily keep and share. We confirm the details when you book."),
      ("Does it include a valuation of the car?", "No. We describe the condition of the bodywork, paint, structure and paperwork, but we do not put a price on the car."),
      ("Can I show it to a buyer?", "Yes, it is designed for that too. It reflects the car's condition on the day we inspected it."),
      ("What does the report not cover?", "Anything outside bodywork, paint, structure and paperwork. We stick to our speciality so that what we tell you is reliable."),
    ],
  },
},
# ---------------------------------------------------------------------------
{
  "slug": "puesta-a-punto-para-vender", "cat": "revision", "icon": "sparkle",
  "es": {
    "titulo": "Puesta a punto para vender",
    "corto": "Pulido, faros, retoques, pequeños golpes y limpieza para que tu coche se vea como está: bien cuidado.",
    "entradilla": "Un coche limpio, con la pintura brillante y los faros claros se vende mejor y más rápido. Lo dejamos presentable sin ocultar nada de su historia.",
    "por_que_titulo": "Por qué ponerlo a punto",
    "por_que": [
      ("camera", "Mejores fotos", "El anuncio es la primera impresión. Una pintura con brillo y unos faros claros se notan mucho en las fotos."),
      ("eye", "Mejor primera visita", "El comprador se fija en los detalles: arañazos, bollos, interior sucio. Cuantos menos vea, más fácil es la conversación."),
      ("shield", "Sin trampas", "Arreglamos y mejoramos, no disimulamos. Si hay reparaciones previas, se pueden ver en el informe."),
    ],
    "incluye_titulo": "Qué podemos hacer",
    "incluye_intro": "Elegimos contigo los trabajos que tienen sentido para tu coche y tu precio de venta.",
    "incluye": [
      ("sparkle", "Pulido y abrillantado", "Quitamos marcas de lavado, arañazos superficiales y aspecto apagado con un [[pulido|pulido]] profesional."),
      ("light", "Restauración de faros", "Devolvemos la transparencia a faros amarillentos u opacos por el sol."),
      ("spray", "Retoques de pintura", "Arañazos en paragolpes, esquinas rozadas y pequeños desconchones en zonas visibles."),
      ("hammer", "Pequeños golpes", "Bollos de aparcamiento y abolladuras pequeñas, a veces sin necesidad de pintar."),
      ("drop", "Limpieza", "Limpieza exterior e interior para que el coche se enseñe cuidado."),
    ],
    "nota": "No todo compensa antes de vender. Te decimos con sinceridad qué merece la pena en tu caso y te damos presupuesto por escrito antes de empezar.",
    "texto": [
      ("h2", "Presentar bien no es esconder"),
      ("p", "Hay una diferencia clara entre poner un coche a punto y maquillarlo. Nosotros hacemos lo primero: dejamos la pintura con brillo, los faros claros, reparamos golpes pequeños y limpiamos el coche. No tapamos daños estructurales ni disimulamos reparaciones mal hechas para que pasen desapercibidas."),
      ("p", "Si quieres vender con total transparencia, puedes combinar la puesta a punto con nuestra [revisión antes de vender](revision-antes-de-vender.html) y enseñar el [informe de carrocería y pintura](informe-de-carroceria-y-pintura.html). El comprador verá un coche cuidado y, además, sabrá exactamente lo que compra."),
      ("h2", "Los trabajos que más se notan"),
      ("checks", [
        "**Pulido y abrillantado.** En Tenerife el sol apaga mucho la pintura. Un [pulido](servicio-pulido-y-abrillantado.html) bien hecho recupera el brillo cuando el barniz está en buen estado.",
        "**Faros.** Unos faros amarillentos hacen que un coche parezca más viejo de lo que es. La [restauración de faros](servicio-restauracion-de-faros.html) suele ser un trabajo que se nota mucho.",
        "**Golpes pequeños.** Un bollo de aparcamiento en una puerta es lo primero que ve el comprador. Muchas veces se puede [reparar](servicio-golpes-y-abolladuras.html) sin pintar la pieza entera.",
        "**Paragolpes y esquinas.** Los roces en las esquinas son muy habituales y tienen fácil solución con un retoque bien hecho.",
        "**Limpieza a fondo.** Un interior limpio y sin olores transmite que el coche se ha cuidado.",
      ]),
      ("h2", "Cómo lo organizamos"),
      ("p", "Nos traes el coche o nos mandas unas fotos para una primera idea. Lo vemos contigo, te proponemos los trabajos que creemos útiles y te damos [presupuesto](presupuesto.html) por escrito. Tú eliges qué hacer. Si hace falta, podemos recoger y entregar el coche según zona y disponibilidad."),
      ("p", "El tiempo depende de los trabajos elegidos y de la carga del taller; te lo confirmamos al aceptar el presupuesto. Si estás pensando en vender, [pide cita](pedir-cita.html) con tiempo para tenerlo listo antes de publicar el anuncio."),
      ("p", "Un consejo: haz las fotos del anuncio justo después de la puesta a punto, con luz de mañana o de última hora de la tarde. El brillo de la pintura y la claridad de los faros se aprecian mucho mejor y el anuncio destaca entre los demás."),
      ("h2", "Y si prefieres no venderlo tú"),
      ("p", "También vendemos coches de segunda mano. Si quieres ver cómo presentamos los nuestros, echa un vistazo a nuestros [coches de ocasión](coches-de-ocasion.html)."),
    ],
    "faq": [
      ("¿La puesta a punto oculta los golpes que haya tenido el coche?", "No. Mejoramos el aspecto y reparamos daños pequeños, pero no disimulamos reparaciones ni daños de estructura. Si quieres, lo acompañamos de un informe honesto."),
      ("¿Merece la pena gastar dinero antes de vender?", "Depende del coche y de su precio. Te decimos con sinceridad qué trabajos compensan y cuáles no."),
      ("¿El pulido quita todos los arañazos?", "Quita los superficiales. Si el arañazo ha atravesado el barniz, hace falta retocar o pintar la zona; te lo explicamos al verlo."),
      ("¿Puedo elegir solo algunos trabajos?", "Claro. El presupuesto va por partidas y tú decides cuáles hacer."),
      ("¿Cuánto tarda?", "Depende de los trabajos elegidos y de la carga del taller. Te damos una previsión al aceptar el presupuesto."),
    ],
  },
  "en": {
    "titulo": "Pre-sale preparation",
    "corto": "Polishing, headlights, touch-ups, small dents and cleaning, so your car looks as it is: well looked after.",
    "entradilla": "A clean car with glossy paint and clear headlights sells better and faster. We make it presentable without hiding anything about its history.",
    "por_que_titulo": "Why prepare it",
    "por_que": [
      ("camera", "Better photos", "The advert is the first impression. Glossy paint and clear headlights really stand out in photos."),
      ("eye", "A better first viewing", "Buyers notice details: scratches, dents, a dirty interior. The fewer they see, the easier the conversation."),
      ("shield", "No tricks", "We repair and improve, we do not disguise. Any earlier repairs can be seen in the report."),
    ],
    "incluye_titulo": "What we can do",
    "incluye_intro": "We choose with you the jobs that make sense for your car and your asking price.",
    "incluye": [
      ("sparkle", "Polishing", "We remove wash marks, light scratches and dullness with professional [[pulido|polishing]]."),
      ("light", "Headlight restoration", "We bring back clarity to headlights yellowed or clouded by the sun."),
      ("spray", "Paint touch-ups", "Scratches on bumpers, scuffed corners and small chips in visible areas."),
      ("hammer", "Small dents", "Car-park dings and small dents, sometimes without the need to paint."),
      ("drop", "Cleaning", "Exterior and interior cleaning so the car shows well."),
    ],
    "nota": "Not everything is worth doing before a sale. We tell you honestly what makes sense in your case and give you a written estimate before we start.",
    "texto": [
      ("h2", "Presenting well is not hiding"),
      ("p", "There is a clear difference between preparing a car and covering things up. We do the first: we bring the paint back to a shine, clear the headlights, fix small dents and clean the car. We do not cover structural damage or disguise poor repairs so they go unnoticed."),
      ("p", "If you want to sell with full transparency, you can combine the preparation with our [pre-sale inspection](revision-antes-de-vender.html) and show the [bodywork and paint report](informe-de-carroceria-y-pintura.html). The buyer sees a well-kept car and also knows exactly what they are buying."),
      ("h2", "The jobs that show most"),
      ("checks", [
        "**Polishing.** In Tenerife the sun dulls paint quickly. Good [polishing](servicio-pulido-y-abrillantado.html) brings back the shine when the clear coat is in good condition.",
        "**Headlights.** Yellowed headlights make a car look older than it is. [Headlight restoration](servicio-restauracion-de-faros.html) is usually a job that makes a real difference.",
        "**Small dents.** A parking ding on a door is the first thing a buyer sees. It can often be [repaired](servicio-golpes-y-abolladuras.html) without painting the whole panel.",
        "**Bumpers and corners.** Scuffed corners are very common and easy to sort with a proper touch-up.",
        "**Thorough cleaning.** A clean interior with no odours tells the buyer the car has been cared for.",
      ]),
      ("h2", "How we organise it"),
      ("p", "Bring the car in or send us a few photos for a first idea. We look at it with you, suggest the jobs we think are useful and give you a written [estimate](presupuesto.html). You choose what to do. If needed, we can collect and return the car depending on the area and availability."),
      ("p", "The time it takes depends on the jobs chosen and how busy the workshop is; we confirm it when you accept the estimate. If you are thinking of selling, [request an appointment](pedir-cita.html) in good time so it is ready before you publish the advert."),
      ("p", "A tip: take the advert photos right after the preparation, in morning or late-afternoon light. The shine of the paint and the clarity of the headlights come across much better and your advert stands out from the rest."),
      ("h2", "If you would rather not sell it yourself"),
      ("p", "We also sell used cars. If you want to see how we present ours, take a look at our [used cars](coches-de-ocasion.html)."),
    ],
    "faq": [
      ("Does the preparation hide any accident damage?", "No. We improve the look and fix minor damage, but we do not disguise repairs or structural damage. If you like, we pair it with an honest report."),
      ("Is it worth spending money before selling?", "It depends on the car and its price. We tell you honestly which jobs pay off and which do not."),
      ("Does polishing remove every scratch?", "It removes light ones. If a scratch has gone through the clear coat, the area needs a touch-up or repaint; we explain when we see it."),
      ("Can I choose only some of the jobs?", "Of course. The estimate is itemised and you decide which to go ahead with."),
      ("How long does it take?", "It depends on the jobs chosen and how busy the workshop is. We give you an estimate of timing when you accept the quote."),
    ],
  },
},
]
